import { NextResponse } from "next/server";

const CKR = [
  {
    train_id: "5025",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-ANGKE",
    dest: "ANGKE",
    time_est: "04:12:00",
    color: "#0084D8",
    dest_time: "05:29:00",
  },
  {
    train_id: "4007",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "04:33:00",
    color: "#0084D8",
    dest_time: "05:45:00",
  },
  {
    train_id: "5503",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "04:44:00",
    color: "#0084D8",
    dest_time: "06:07:00",
  },
  {
    train_id: "5031",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "04:51:00",
    color: "#0084D8",
    dest_time: "06:13:00",
  },
  {
    train_id: "4009",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "05:06:00",
    color: "#0084D8",
    dest_time: "06:14:00",
  },
  {
    train_id: "5039",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-ANGKE",
    dest: "ANGKE",
    time_est: "05:21:00",
    color: "#0084D8",
    dest_time: "06:41:00",
  },
  {
    train_id: "5507",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "05:30:00",
    color: "#0084D8",
    dest_time: "06:54:00",
  },
  {
    train_id: "4011",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "05:39:00",
    color: "#0084D8",
    dest_time: "06:45:00",
  },
  {
    train_id: "5509",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "05:46:00",
    color: "#0084D8",
    dest_time: "07:17:00",
  },
  {
    train_id: "320",
    ka_name: "Commuter Line Walahar",
    route_name: "CIKARANG-PURWAKARTA",
    dest: "PURWAKARTA",
    time_est: "05:50:00",
    color: "#0084D8",
    dest_time: "07:06:00",
  },
  {
    train_id: "4013",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "06:09:00",
    color: "#0084D8",
    dest_time: "07:15:00",
  },
  {
    train_id: "5511",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "06:14:00",
    color: "#0084D8",
    dest_time: "07:38:00",
  },
  {
    train_id: "5513",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "06:25:00",
    color: "#0084D8",
    dest_time: "07:49:00",
  },
  {
    train_id: "5515A",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-ANGKE",
    dest: "ANGKE",
    time_est: "06:38:00",
    color: "#0084D8",
    dest_time: "07:58:00",
  },
  {
    train_id: "5517A",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-ANGKE",
    dest: "ANGKE",
    time_est: "06:45:00",
    color: "#0084D8",
    dest_time: "08:09:00",
  },
  {
    train_id: "5049",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-ANGKE",
    dest: "ANGKE",
    time_est: "07:11:00",
    color: "#0084D8",
    dest_time: "08:29:00",
  },
  {
    train_id: "316",
    ka_name: "Commuter Line Walahar",
    route_name: "CIKARANG-PURWAKARTA",
    dest: "PURWAKARTA",
    time_est: "07:24:00",
    color: "#0084D8",
    dest_time: "09:04:00",
  },
  {
    train_id: "5051",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-ANGKE",
    dest: "ANGKE",
    time_est: "07:24:00",
    color: "#0084D8",
    dest_time: "08:43:00",
  },
  {
    train_id: "4025A",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "07:47:00",
    color: "#0084D8",
    dest_time: "08:52:00",
  },
  {
    train_id: "5529B",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "08:11:00",
    color: "#0084D8",
    dest_time: "09:37:00",
  },
  {
    train_id: "5531",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "08:21:00",
    color: "#0084D8",
    dest_time: "09:50:00",
  },
  {
    train_id: "4029",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "08:36:00",
    color: "#0084D8",
    dest_time: "09:48:00",
  },
  {
    train_id: "5063",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-ANGKE",
    dest: "ANGKE",
    time_est: "08:58:00",
    color: "#0084D8",
    dest_time: "10:12:00",
  },
  {
    train_id: "5065",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-ANGKE",
    dest: "ANGKE",
    time_est: "09:15:00",
    color: "#0084D8",
    dest_time: "10:30:00",
  },
  {
    train_id: "4033",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "09:32:00",
    color: "#0084D8",
    dest_time: "10:39:00",
  },
  {
    train_id: "5539",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "10:00:00",
    color: "#0084D8",
    dest_time: "11:24:00",
  },
  {
    train_id: "5075",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-ANGKE",
    dest: "ANGKE",
    time_est: "10:12:00",
    color: "#0084D8",
    dest_time: "11:28:00",
  },
  {
    train_id: "5079",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-ANGKE",
    dest: "ANGKE",
    time_est: "10:30:00",
    color: "#0084D8",
    dest_time: "11:45:00",
  },
  {
    train_id: "5083A",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "11:09:00",
    color: "#0084D8",
    dest_time: "12:29:00",
  },
  {
    train_id: "5545",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "11:19:00",
    color: "#0084D8",
    dest_time: "12:46:00",
  },
  {
    train_id: "322",
    ka_name: "Commuter Line Walahar",
    route_name: "CIKARANG-PURWAKARTA",
    dest: "PURWAKARTA",
    time_est: "11:30:00",
    color: "#0084D8",
    dest_time: "12:57:00",
  },
  {
    train_id: "5087",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-ANGKE",
    dest: "ANGKE",
    time_est: "11:31:00",
    color: "#0084D8",
    dest_time: "12:44:00",
  },
  {
    train_id: "4047",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "11:50:00",
    color: "#0084D8",
    dest_time: "12:55:00",
  },
  {
    train_id: "5093",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "12:00:00",
    color: "#0084D8",
    dest_time: "13:28:00",
  },
  {
    train_id: "5549",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "12:19:00",
    color: "#0084D8",
    dest_time: "13:44:00",
  },
  {
    train_id: "5099",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "12:43:00",
    color: "#0084D8",
    dest_time: "14:07:00",
  },
  {
    train_id: "4055",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "12:51:00",
    color: "#0084D8",
    dest_time: "13:59:00",
  },
  {
    train_id: "5555",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "13:17:00",
    color: "#0084D8",
    dest_time: "14:44:00",
  },
  {
    train_id: "318",
    ka_name: "Commuter Line Walahar",
    route_name: "CIKARANG-PURWAKARTA",
    dest: "PURWAKARTA",
    time_est: "13:20:00",
    color: "#0084D8",
    dest_time: "14:52:00",
  },
  {
    train_id: "5107",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-ANGKE",
    dest: "ANGKE",
    time_est: "13:37:00",
    color: "#0084D8",
    dest_time: "14:58:00",
  },
  {
    train_id: "4061A",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "14:13:00",
    color: "#0084D8",
    dest_time: "15:19:00",
  },
  {
    train_id: "4063",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "14:30:00",
    color: "#0084D8",
    dest_time: "15:38:00",
  },
  {
    train_id: "4065",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "14:55:00",
    color: "#0084D8",
    dest_time: "16:00:00",
  },
  {
    train_id: "5121",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-ANGKE",
    dest: "ANGKE",
    time_est: "15:14:00",
    color: "#0084D8",
    dest_time: "16:28:00",
  },
  {
    train_id: "5567",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "15:20:00",
    color: "#0084D8",
    dest_time: "16:46:00",
  },
  {
    train_id: "4069",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "15:32:00",
    color: "#0084D8",
    dest_time: "16:38:00",
  },
  {
    train_id: "5569",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "15:37:00",
    color: "#0084D8",
    dest_time: "17:09:00",
  },
  {
    train_id: "5127",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "15:52:00",
    color: "#0084D8",
    dest_time: "17:14:00",
  },
  {
    train_id: "5129",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-ANGKE",
    dest: "ANGKE",
    time_est: "16:01:00",
    color: "#0084D8",
    dest_time: "17:18:00",
  },
  {
    train_id: "5131",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-ANGKE",
    dest: "ANGKE",
    time_est: "16:23:00",
    color: "#0084D8",
    dest_time: "17:39:00",
  },
  {
    train_id: "5135A",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-ANGKE",
    dest: "ANGKE",
    time_est: "16:42:00",
    color: "#0084D8",
    dest_time: "18:03:00",
  },
  {
    train_id: "5137",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-ANGKE",
    dest: "ANGKE",
    time_est: "16:55:00",
    color: "#0084D8",
    dest_time: "18:13:00",
  },
  {
    train_id: "5577A",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "17:21:00",
    color: "#0084D8",
    dest_time: "18:45:00",
  },
  {
    train_id: "4083",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "17:36:00",
    color: "#0084D8",
    dest_time: "18:40:00",
  },
  {
    train_id: "4085",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "17:47:00",
    color: "#0084D8",
    dest_time: "18:54:00",
  },
  {
    train_id: "5581",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "17:53:00",
    color: "#0084D8",
    dest_time: "19:15:00",
  },
  {
    train_id: "5583",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "18:09:00",
    color: "#0084D8",
    dest_time: "19:39:00",
  },
  {
    train_id: "5149",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-ANGKE",
    dest: "ANGKE",
    time_est: "18:25:00",
    color: "#0084D8",
    dest_time: "19:40:00",
  },
  {
    train_id: "5585",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "18:30:00",
    color: "#0084D8",
    dest_time: "19:59:00",
  },
  {
    train_id: "324",
    ka_name: "Commuter Line Walahar",
    route_name: "CIKARANG-PURWAKARTA",
    dest: "PURWAKARTA",
    time_est: "18:45:00",
    color: "#0084D8",
    dest_time: "20:35:00",
  },
  {
    train_id: "5153A",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-ANGKE",
    dest: "ANGKE",
    time_est: "18:46:00",
    color: "#0084D8",
    dest_time: "20:08:00",
  },
  {
    train_id: "4093",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "19:01:00",
    color: "#0084D8",
    dest_time: "20:11:00",
  },
  {
    train_id: "5587B",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "19:13:00",
    color: "#0084D8",
    dest_time: "20:46:00",
  },
  {
    train_id: "4095",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "19:23:00",
    color: "#0084D8",
    dest_time: "20:39:00",
  },
  {
    train_id: "5589",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "19:36:00",
    color: "#0084D8",
    dest_time: "20:59:00",
  },
  {
    train_id: "4097",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "19:47:00",
    color: "#0084D8",
    dest_time: "20:52:00",
  },
  {
    train_id: "4099",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "19:56:00",
    color: "#0084D8",
    dest_time: "21:08:00",
  },
  {
    train_id: "328",
    ka_name: "Commuter Line Jatiluhur",
    route_name: "CIKARANG-CIKAMPEK",
    dest: "CIKAMPEK",
    time_est: "20:02:00",
    color: "#0084D8",
    dest_time: "21:22:00",
  },
  {
    train_id: "5163",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "20:10:00",
    color: "#0084D8",
    dest_time: "21:37:00",
  },
  {
    train_id: "4101",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "20:25:00",
    color: "#0084D8",
    dest_time: "21:38:00",
  },
  {
    train_id: "5165",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-ANGKE",
    dest: "ANGKE",
    time_est: "20:36:00",
    color: "#0084D8",
    dest_time: "21:50:00",
  },
  {
    train_id: "5167",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "20:45:00",
    color: "#0084D8",
    dest_time: "22:14:00",
  },
  {
    train_id: "4103",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "20:56:00",
    color: "#0084D8",
    dest_time: "22:00:00",
  },
  {
    train_id: "5597",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "21:15:00",
    color: "#0084D8",
    dest_time: "22:37:00",
  },
  {
    train_id: "4105",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "21:21:00",
    color: "#0084D8",
    dest_time: "22:29:00",
  },
  {
    train_id: "4107",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-KAMPUNGBANDAN",
    dest: "KAMPUNGBANDAN",
    time_est: "21:42:00",
    color: "#0084D8",
    dest_time: "22:48:00",
  },
  {
    train_id: "5179",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "22:15:00",
    color: "#0084D8",
    dest_time: "23:05:00",
  },
  {
    train_id: "5181",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-ANGKE",
    dest: "ANGKE",
    time_est: "22:27:00",
    color: "#0084D8",
    dest_time: "23:38:00",
  },
  {
    train_id: "5183A",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-ANGKE",
    dest: "ANGKE",
    time_est: "22:35:00",
    color: "#0084D8",
    dest_time: "23:50:00",
  },
  {
    train_id: "5185A",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "22:56:00",
    color: "#0084D8",
    dest_time: "23:53:00",
  },
];

export async function GET() {
  const response = {
    status: 200,
    message: "Success",
    data: CKR,
  };

  return NextResponse.json(response); // Mengembalikan respons JSON
}
