import { NextResponse } from "next/server";

const AC = [
  {
    train_id: "2400",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "06:16:00",
    color: "#DD0067",
    dest_time: "06:16:00",
  },
  {
    train_id: "2401A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:32:00",
    color: "#DD0067",
    dest_time: "06:36:00",
  },
  {
    train_id: "2402A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "06:36:00",
    color: "#DD0067",
    dest_time: "06:36:00",
  },
  {
    train_id: "2403A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:52:00",
    color: "#DD0067",
    dest_time: "06:56:00",
  },
  {
    train_id: "2404A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "06:56:00",
    color: "#DD0067",
    dest_time: "06:56:00",
  },
  {
    train_id: "2405A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:12:00",
    color: "#DD0067",
    dest_time: "07:16:00",
  },
  {
    train_id: "2406A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "07:16:00",
    color: "#DD0067",
    dest_time: "07:16:00",
  },
  {
    train_id: "2407A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:32:00",
    color: "#DD0067",
    dest_time: "07:36:00",
  },
  {
    train_id: "2408A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "07:36:00",
    color: "#DD0067",
    dest_time: "07:36:00",
  },
  {
    train_id: "2409A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:52:00",
    color: "#DD0067",
    dest_time: "07:56:00",
  },
  {
    train_id: "2410A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "07:56:00",
    color: "#DD0067",
    dest_time: "07:56:00",
  },
  {
    train_id: "2411A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:12:00",
    color: "#DD0067",
    dest_time: "08:16:00",
  },
  {
    train_id: "2412A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "08:16:00",
    color: "#DD0067",
    dest_time: "08:16:00",
  },
  {
    train_id: "2413A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:32:00",
    color: "#DD0067",
    dest_time: "08:36:00",
  },
  {
    train_id: "2414A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "08:36:00",
    color: "#DD0067",
    dest_time: "08:36:00",
  },
  {
    train_id: "2415A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:52:00",
    color: "#DD0067",
    dest_time: "08:56:00",
  },
  {
    train_id: "2416A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "08:56:00",
    color: "#DD0067",
    dest_time: "08:56:00",
  },
  {
    train_id: "2417A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:12:00",
    color: "#DD0067",
    dest_time: "09:16:00",
  },
  {
    train_id: "2418A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "09:16:00",
    color: "#DD0067",
    dest_time: "09:16:00",
  },
  {
    train_id: "2419A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:32:00",
    color: "#DD0067",
    dest_time: "09:36:00",
  },
  {
    train_id: "2420A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "09:36:00",
    color: "#DD0067",
    dest_time: "09:36:00",
  },
  {
    train_id: "2421A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:52:00",
    color: "#DD0067",
    dest_time: "09:56:00",
  },
  {
    train_id: "2422A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "09:56:00",
    color: "#DD0067",
    dest_time: "09:56:00",
  },
  {
    train_id: "2423A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:12:00",
    color: "#DD0067",
    dest_time: "10:16:00",
  },
  {
    train_id: "2424A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "10:16:00",
    color: "#DD0067",
    dest_time: "10:16:00",
  },
  {
    train_id: "2425A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:32:00",
    color: "#DD0067",
    dest_time: "10:36:00",
  },
  {
    train_id: "2426A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "10:36:00",
    color: "#DD0067",
    dest_time: "10:36:00",
  },
  {
    train_id: "2427A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:52:00",
    color: "#DD0067",
    dest_time: "10:56:00",
  },
  {
    train_id: "2428A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "10:56:00",
    color: "#DD0067",
    dest_time: "10:56:00",
  },
  {
    train_id: "2429A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:12:00",
    color: "#DD0067",
    dest_time: "11:16:00",
  },
  {
    train_id: "2430A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "11:16:00",
    color: "#DD0067",
    dest_time: "11:16:00",
  },
  {
    train_id: "2431A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:32:00",
    color: "#DD0067",
    dest_time: "11:36:00",
  },
  {
    train_id: "2432A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "11:36:00",
    color: "#DD0067",
    dest_time: "11:36:00",
  },
  {
    train_id: "2490B",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "11:47:00",
    color: "#DD0067",
    dest_time: "11:56:00",
  },
  {
    train_id: "2433A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:52:00",
    color: "#DD0067",
    dest_time: "11:56:00",
  },
  {
    train_id: "2491B",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "12:08:00",
    color: "#DD0067",
    dest_time: "12:16:00",
  },
  {
    train_id: "2438A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "12:36:00",
    color: "#DD0067",
    dest_time: "12:36:00",
  },
  {
    train_id: "2439A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "12:52:00",
    color: "#DD0067",
    dest_time: "12:56:00",
  },
  {
    train_id: "2442A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "13:16:00",
    color: "#DD0067",
    dest_time: "13:16:00",
  },
  {
    train_id: "2443A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "13:32:00",
    color: "#DD0067",
    dest_time: "13:36:00",
  },
  {
    train_id: "2444A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "13:36:00",
    color: "#DD0067",
    dest_time: "13:36:00",
  },
  {
    train_id: "2436B",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "13:47:00",
    color: "#DD0067",
    dest_time: "13:56:00",
  },
  {
    train_id: "2445A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "13:52:00",
    color: "#DD0067",
    dest_time: "13:56:00",
  },
  {
    train_id: "2437B",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:08:00",
    color: "#DD0067",
    dest_time: "14:16:00",
  },
  {
    train_id: "2448A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "14:16:00",
    color: "#DD0067",
    dest_time: "14:16:00",
  },
  {
    train_id: "2449A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:32:00",
    color: "#DD0067",
    dest_time: "14:36:00",
  },
  {
    train_id: "2450A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "14:36:00",
    color: "#DD0067",
    dest_time: "14:36:00",
  },
  {
    train_id: "2494B",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "14:47:00",
    color: "#DD0067",
    dest_time: "14:56:00",
  },
  {
    train_id: "2451A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:52:00",
    color: "#DD0067",
    dest_time: "14:56:00",
  },
  {
    train_id: "2495B",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:08:00",
    color: "#DD0067",
    dest_time: "15:16:00",
  },
  {
    train_id: "2454A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "15:16:00",
    color: "#DD0067",
    dest_time: "15:16:00",
  },
  {
    train_id: "2455A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:32:00",
    color: "#DD0067",
    dest_time: "15:36:00",
  },
  {
    train_id: "2456A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "15:36:00",
    color: "#DD0067",
    dest_time: "15:36:00",
  },
  {
    train_id: "2496B",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "15:47:00",
    color: "#DD0067",
    dest_time: "15:56:00",
  },
  {
    train_id: "2457A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:52:00",
    color: "#DD0067",
    dest_time: "15:56:00",
  },
  {
    train_id: "2497B",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:08:00",
    color: "#DD0067",
    dest_time: "16:16:00",
  },
  {
    train_id: "2460A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "16:16:00",
    color: "#DD0067",
    dest_time: "16:16:00",
  },
  {
    train_id: "2461A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:32:00",
    color: "#DD0067",
    dest_time: "16:36:00",
  },
  {
    train_id: "2462A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "16:36:00",
    color: "#DD0067",
    dest_time: "16:36:00",
  },
  {
    train_id: "2463A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:52:00",
    color: "#DD0067",
    dest_time: "16:56:00",
  },
  {
    train_id: "2464A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "16:56:00",
    color: "#DD0067",
    dest_time: "16:56:00",
  },
  {
    train_id: "2465A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:12:00",
    color: "#DD0067",
    dest_time: "17:16:00",
  },
  {
    train_id: "2466A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "17:16:00",
    color: "#DD0067",
    dest_time: "17:16:00",
  },
  {
    train_id: "2467A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:32:00",
    color: "#DD0067",
    dest_time: "17:36:00",
  },
  {
    train_id: "2468A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "17:36:00",
    color: "#DD0067",
    dest_time: "17:36:00",
  },
  {
    train_id: "2469A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:52:00",
    color: "#DD0067",
    dest_time: "17:56:00",
  },
  {
    train_id: "2470A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "17:56:00",
    color: "#DD0067",
    dest_time: "17:56:00",
  },
  {
    train_id: "2471A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:12:00",
    color: "#DD0067",
    dest_time: "18:16:00",
  },
  {
    train_id: "2472A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "18:16:00",
    color: "#DD0067",
    dest_time: "18:16:00",
  },
  {
    train_id: "2473A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:32:00",
    color: "#DD0067",
    dest_time: "18:36:00",
  },
  {
    train_id: "2474A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "18:36:00",
    color: "#DD0067",
    dest_time: "18:36:00",
  },
  {
    train_id: "2475A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:52:00",
    color: "#DD0067",
    dest_time: "18:56:00",
  },
  {
    train_id: "2476A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "18:56:00",
    color: "#DD0067",
    dest_time: "18:56:00",
  },
  {
    train_id: "2477A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:12:00",
    color: "#DD0067",
    dest_time: "19:16:00",
  },
  {
    train_id: "2478A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "19:16:00",
    color: "#DD0067",
    dest_time: "19:16:00",
  },
  {
    train_id: "2479A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:32:00",
    color: "#DD0067",
    dest_time: "19:36:00",
  },
  {
    train_id: "2480A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "19:36:00",
    color: "#DD0067",
    dest_time: "19:36:00",
  },
  {
    train_id: "2481A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:52:00",
    color: "#DD0067",
    dest_time: "19:56:00",
  },
  {
    train_id: "2482A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "19:56:00",
    color: "#DD0067",
    dest_time: "19:56:00",
  },
  {
    train_id: "2483A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "20:12:00",
    color: "#DD0067",
    dest_time: "20:16:00",
  },
  {
    train_id: "2484A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "20:16:00",
    color: "#DD0067",
    dest_time: "20:16:00",
  },
  {
    train_id: "2485A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "20:32:00",
    color: "#DD0067",
    dest_time: "20:36:00",
  },
  {
    train_id: "2486A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "20:36:00",
    color: "#DD0067",
    dest_time: "20:36:00",
  },
  {
    train_id: "2487A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "20:52:00",
    color: "#DD0067",
    dest_time: "20:56:00",
  },
  {
    train_id: "2488A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "20:56:00",
    color: "#DD0067",
    dest_time: "20:56:00",
  },
  {
    train_id: "2489A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "21:12:00",
    color: "#DD0067",
    dest_time: "21:16:00",
  },
];

export async function GET() {
  const response = {
    status: 200,
    message: "Success",
    data: AC,
  };

  return NextResponse.json(response); // Mengembalikan respons JSON
}