import { NextResponse } from "next/server";

const MJ = [
  {
    train_id: "1820",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "00:04:00",
    color: "#16812B",
    dest_time: "00:27:00",
  },
  {
    train_id: "D1/R1816-3",
    ka_name: "DINAS RANGKAIAN KRL (TIDAK ANGKUT PENUMPANG)",
    route_name: "RANGKASBITUNG-PARUNGPANJANG",
    dest: "PARUNGPANJANG",
    time_est: "00:21:00",
    color: "#16812B",
    dest_time: "00:48:00",
  },
  {
    train_id: "1826A",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "00:42:00",
    color: "#16812B",
    dest_time: "01:05:00",
  },
  {
    train_id: "D1/R1633-2",
    ka_name: "DINAS RANGKAIAN KRL (TIDAK ANGKUT PENUMPANG)",
    route_name: "PARUNGPANJANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "03:48:00",
    color: "#16812B",
    dest_time: "04:09:00",
  },
  {
    train_id: "1604",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "PARUNGPANJANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "04:22:00",
    color: "#16812B",
    dest_time: "04:45:00",
  },
  {
    train_id: "1629",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "04:24:00",
    color: "#16812B",
    dest_time: "05:47:00",
  },
  {
    train_id: "1606",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "PARUNGPANJANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "04:36:00",
    color: "#16812B",
    dest_time: "04:59:00",
  },
  {
    train_id: "1633",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "04:44:00",
    color: "#16812B",
    dest_time: "06:07:00",
  },
  {
    train_id: "1610",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "PARUNGPANJANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "05:01:00",
    color: "#16812B",
    dest_time: "05:24:00",
  },
  {
    train_id: "1637",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "05:04:00",
    color: "#16812B",
    dest_time: "06:27:00",
  },
  {
    train_id: "1641",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "05:24:00",
    color: "#16812B",
    dest_time: "06:47:00",
  },
  {
    train_id: "1612",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "PARUNGPANJANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "05:41:00",
    color: "#16812B",
    dest_time: "06:05:00",
  },
  {
    train_id: "1645A",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "05:42:00",
    color: "#16812B",
    dest_time: "07:07:00",
  },
  {
    train_id: "1647",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "05:54:00",
    color: "#16812B",
    dest_time: "07:17:00",
  },
  {
    train_id: "1614",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "PARUNGPANJANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "05:56:00",
    color: "#16812B",
    dest_time: "06:19:00",
  },
  {
    train_id: "1616",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "SERPONG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "06:11:00",
    color: "#16812B",
    dest_time: "06:34:00",
  },
  {
    train_id: "1651",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "06:11:00",
    color: "#16812B",
    dest_time: "07:37:00",
  },
  {
    train_id: "1618",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "06:26:00",
    color: "#16812B",
    dest_time: "06:49:00",
  },
  {
    train_id: "1655",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "06:27:00",
    color: "#16812B",
    dest_time: "07:57:00",
  },
  {
    train_id: "1657",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "06:41:00",
    color: "#16812B",
    dest_time: "08:07:00",
  },
  {
    train_id: "1622A",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "06:44:00",
    color: "#16812B",
    dest_time: "07:07:00",
  },
  {
    train_id: "1659",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "06:54:00",
    color: "#16812B",
    dest_time: "08:17:00",
  },
  {
    train_id: "1663",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "07:12:00",
    color: "#16812B",
    dest_time: "08:37:00",
  },
  {
    train_id: "1628",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "07:15:00",
    color: "#16812B",
    dest_time: "07:39:00",
  },
  {
    train_id: "1630",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "07:28:00",
    color: "#16812B",
    dest_time: "07:53:00",
  },
  {
    train_id: "1667",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "07:34:00",
    color: "#16812B",
    dest_time: "08:57:00",
  },
  {
    train_id: "1634A",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "07:46:00",
    color: "#16812B",
    dest_time: "08:09:00",
  },
  {
    train_id: "1671",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "07:54:00",
    color: "#16812B",
    dest_time: "09:17:00",
  },
  {
    train_id: "1636B",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "07:58:00",
    color: "#16812B",
    dest_time: "08:23:00",
  },
  {
    train_id: "1675",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "08:12:00",
    color: "#16812B",
    dest_time: "09:37:00",
  },
  {
    train_id: "1640",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "08:14:00",
    color: "#16812B",
    dest_time: "08:37:00",
  },
  {
    train_id: "1642",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "08:27:00",
    color: "#16812B",
    dest_time: "08:51:00",
  },
  {
    train_id: "1679A",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "08:28:00",
    color: "#16812B",
    dest_time: "09:55:00",
  },
  {
    train_id: "1646",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "08:44:00",
    color: "#16812B",
    dest_time: "09:07:00",
  },
  {
    train_id: "1683",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "08:54:00",
    color: "#16812B",
    dest_time: "10:17:00",
  },
  {
    train_id: "1648A",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "08:59:00",
    color: "#16812B",
    dest_time: "09:22:00",
  },
  {
    train_id: "1687",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "09:11:00",
    color: "#16812B",
    dest_time: "10:37:00",
  },
  {
    train_id: "1652",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "09:14:00",
    color: "#16812B",
    dest_time: "09:37:00",
  },
  {
    train_id: "1689",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "09:24:00",
    color: "#16812B",
    dest_time: "10:47:00",
  },
  {
    train_id: "1654",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "09:28:00",
    color: "#16812B",
    dest_time: "09:51:00",
  },
  {
    train_id: "1693",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "09:41:00",
    color: "#16812B",
    dest_time: "11:07:00",
  },
  {
    train_id: "1658",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "09:44:00",
    color: "#16812B",
    dest_time: "10:07:00",
  },
  {
    train_id: "1695",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "09:54:00",
    color: "#16812B",
    dest_time: "11:17:00",
  },
  {
    train_id: "1660",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "09:57:00",
    color: "#16812B",
    dest_time: "10:21:00",
  },
  {
    train_id: "1699",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "10:12:00",
    color: "#16812B",
    dest_time: "11:37:00",
  },
  {
    train_id: "1664",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "10:14:00",
    color: "#16812B",
    dest_time: "10:37:00",
  },
  {
    train_id: "1703A",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "10:24:00",
    color: "#16812B",
    dest_time: "11:47:00",
  },
  {
    train_id: "1666",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "10:28:00",
    color: "#16812B",
    dest_time: "10:51:00",
  },
  {
    train_id: "1705",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "10:41:00",
    color: "#16812B",
    dest_time: "12:07:00",
  },
  {
    train_id: "1707",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "10:54:00",
    color: "#16812B",
    dest_time: "12:17:00",
  },
  {
    train_id: "1672",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "10:58:00",
    color: "#16812B",
    dest_time: "11:21:00",
  },
  {
    train_id: "1711",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "11:11:00",
    color: "#16812B",
    dest_time: "12:37:00",
  },
  {
    train_id: "1676",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "11:14:00",
    color: "#16812B",
    dest_time: "11:36:00",
  },
  {
    train_id: "1713",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "11:24:00",
    color: "#16812B",
    dest_time: "12:47:00",
  },
  {
    train_id: "1678",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "11:27:00",
    color: "#16812B",
    dest_time: "11:50:00",
  },
  {
    train_id: "1717",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "11:42:00",
    color: "#16812B",
    dest_time: "13:07:00",
  },
  {
    train_id: "1686",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "12:04:00",
    color: "#16812B",
    dest_time: "12:27:00",
  },
  {
    train_id: "1723",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "12:11:00",
    color: "#16812B",
    dest_time: "13:37:00",
  },
  {
    train_id: "1690",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "12:24:00",
    color: "#16812B",
    dest_time: "12:47:00",
  },
  {
    train_id: "1725",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "12:24:00",
    color: "#16812B",
    dest_time: "13:47:00",
  },
  {
    train_id: "1694",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "12:44:00",
    color: "#16812B",
    dest_time: "13:07:00",
  },
  {
    train_id: "1729",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "12:54:00",
    color: "#16812B",
    dest_time: "14:17:00",
  },
  {
    train_id: "1696",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "12:57:00",
    color: "#16812B",
    dest_time: "13:21:00",
  },
  {
    train_id: "1700",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "13:14:00",
    color: "#16812B",
    dest_time: "13:37:00",
  },
  {
    train_id: "1733",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "13:17:00",
    color: "#16812B",
    dest_time: "14:40:00",
  },
  {
    train_id: "1704A",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "13:28:00",
    color: "#16812B",
    dest_time: "13:54:00",
  },
  {
    train_id: "1737",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "13:34:00",
    color: "#16812B",
    dest_time: "14:57:00",
  },
  {
    train_id: "1706",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "13:44:00",
    color: "#16812B",
    dest_time: "14:08:00",
  },
  {
    train_id: "1741",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "13:52:00",
    color: "#16812B",
    dest_time: "15:17:00",
  },
  {
    train_id: "1708",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "13:58:00",
    color: "#16812B",
    dest_time: "14:22:00",
  },
  {
    train_id: "1743",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "14:04:00",
    color: "#16812B",
    dest_time: "15:27:00",
  },
  {
    train_id: "1712",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "14:14:00",
    color: "#16812B",
    dest_time: "14:37:00",
  },
  {
    train_id: "1747",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "14:22:00",
    color: "#16812B",
    dest_time: "15:47:00",
  },
  {
    train_id: "1714",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "14:27:00",
    color: "#16812B",
    dest_time: "14:51:00",
  },
  {
    train_id: "1749",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "14:34:00",
    color: "#16812B",
    dest_time: "15:57:00",
  },
  {
    train_id: "1718",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "14:44:00",
    color: "#16812B",
    dest_time: "15:07:00",
  },
  {
    train_id: "1753",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "14:54:00",
    color: "#16812B",
    dest_time: "16:17:00",
  },
  {
    train_id: "1720",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "14:58:00",
    color: "#16812B",
    dest_time: "15:21:00",
  },
  {
    train_id: "1757",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "15:11:00",
    color: "#16812B",
    dest_time: "16:37:00",
  },
  {
    train_id: "1724",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "15:14:00",
    color: "#16812B",
    dest_time: "15:37:00",
  },
  {
    train_id: "1759",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "15:24:00",
    color: "#16812B",
    dest_time: "16:47:00",
  },
  {
    train_id: "1726",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "15:28:00",
    color: "#16812B",
    dest_time: "15:51:00",
  },
  {
    train_id: "1763",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "15:42:00",
    color: "#16812B",
    dest_time: "17:07:00",
  },
  {
    train_id: "1730",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "15:44:00",
    color: "#16812B",
    dest_time: "16:07:00",
  },
  {
    train_id: "1765",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "15:54:00",
    color: "#16812B",
    dest_time: "17:17:00",
  },
  {
    train_id: "1769",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "16:11:00",
    color: "#16812B",
    dest_time: "17:37:00",
  },
  {
    train_id: "1734",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "16:14:00",
    color: "#16812B",
    dest_time: "16:37:00",
  },
  {
    train_id: "1771",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "16:24:00",
    color: "#16812B",
    dest_time: "17:47:00",
  },
  {
    train_id: "1736",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "16:28:00",
    color: "#16812B",
    dest_time: "16:51:00",
  },
  {
    train_id: "1775",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "16:41:00",
    color: "#16812B",
    dest_time: "18:07:00",
  },
  {
    train_id: "1742",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "16:54:00",
    color: "#16812B",
    dest_time: "17:17:00",
  },
  {
    train_id: "1777",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "16:54:00",
    color: "#16812B",
    dest_time: "18:17:00",
  },
  {
    train_id: "1744",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "17:08:00",
    color: "#16812B",
    dest_time: "17:31:00",
  },
  {
    train_id: "1748",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "17:24:00",
    color: "#16812B",
    dest_time: "17:47:00",
  },
  {
    train_id: "1783",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "17:24:00",
    color: "#16812B",
    dest_time: "18:47:00",
  },
  {
    train_id: "1750",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "17:38:00",
    color: "#16812B",
    dest_time: "18:01:00",
  },
  {
    train_id: "1787",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "17:42:00",
    color: "#16812B",
    dest_time: "19:07:00",
  },
  {
    train_id: "1752",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "17:50:00",
    color: "#16812B",
    dest_time: "18:15:00",
  },
  {
    train_id: "1791",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "18:02:00",
    color: "#16812B",
    dest_time: "19:27:00",
  },
  {
    train_id: "1756",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "18:05:00",
    color: "#16812B",
    dest_time: "18:29:00",
  },
  {
    train_id: "1795",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "18:22:00",
    color: "#16812B",
    dest_time: "19:47:00",
  },
  {
    train_id: "1760",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "18:24:00",
    color: "#16812B",
    dest_time: "18:47:00",
  },
  {
    train_id: "1797",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "18:34:00",
    color: "#16812B",
    dest_time: "19:57:00",
  },
  {
    train_id: "1764",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "18:44:00",
    color: "#16812B",
    dest_time: "19:07:00",
  },
  {
    train_id: "1801",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "18:51:00",
    color: "#16812B",
    dest_time: "20:17:00",
  },
  {
    train_id: "1768",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "19:04:00",
    color: "#16812B",
    dest_time: "19:27:00",
  },
  {
    train_id: "1803A",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-SERPONG",
    dest: "SERPONG",
    time_est: "19:04:00",
    color: "#16812B",
    dest_time: "19:49:00",
  },
  {
    train_id: "1772",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "19:24:00",
    color: "#16812B",
    dest_time: "19:47:00",
  },
  {
    train_id: "1774",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "19:38:00",
    color: "#16812B",
    dest_time: "20:01:00",
  },
  {
    train_id: "1809",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "19:43:00",
    color: "#16812B",
    dest_time: "21:09:00",
  },
  {
    train_id: "1778",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "19:54:00",
    color: "#16812B",
    dest_time: "20:17:00",
  },
  {
    train_id: "1811",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "20:00:00",
    color: "#16812B",
    dest_time: "21:23:00",
  },
  {
    train_id: "1780A",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "20:08:00",
    color: "#16812B",
    dest_time: "20:31:00",
  },
  {
    train_id: "1813",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "20:14:00",
    color: "#16812B",
    dest_time: "21:37:00",
  },
  {
    train_id: "1784A",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "20:25:00",
    color: "#16812B",
    dest_time: "20:49:00",
  },
  {
    train_id: "1815",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "20:29:00",
    color: "#16812B",
    dest_time: "21:52:00",
  },
  {
    train_id: "1786",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "20:38:00",
    color: "#16812B",
    dest_time: "21:03:00",
  },
  {
    train_id: "1817",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "20:44:00",
    color: "#16812B",
    dest_time: "22:07:00",
  },
  {
    train_id: "1819",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "20:59:00",
    color: "#16812B",
    dest_time: "22:22:00",
  },
  {
    train_id: "1792",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "21:08:00",
    color: "#16812B",
    dest_time: "21:31:00",
  },
  {
    train_id: "1821",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "21:15:00",
    color: "#16812B",
    dest_time: "22:38:00",
  },
  {
    train_id: "1796",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "21:24:00",
    color: "#16812B",
    dest_time: "21:47:00",
  },
  {
    train_id: "1823",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-SERPONG",
    dest: "SERPONG",
    time_est: "21:29:00",
    color: "#16812B",
    dest_time: "22:15:00",
  },
  {
    train_id: "1798",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "21:38:00",
    color: "#16812B",
    dest_time: "22:01:00",
  },
  {
    train_id: "1825",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-TANAHABANG",
    dest: "TANAHABANG",
    time_est: "21:43:00",
    color: "#16812B",
    dest_time: "23:06:00",
  },
  {
    train_id: "1804",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "22:08:00",
    color: "#16812B",
    dest_time: "22:31:00",
  },
  {
    train_id: "1806",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "22:24:00",
    color: "#16812B",
    dest_time: "22:47:00",
  },
  {
    train_id: "1831",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-SERPONG",
    dest: "SERPONG",
    time_est: "22:26:00",
    color: "#16812B",
    dest_time: "23:12:00",
  },
  {
    train_id: "1810",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "TANAHABANG-RANGKASBITUNG",
    dest: "RANGKASBITUNG",
    time_est: "22:44:00",
    color: "#16812B",
    dest_time: "23:07:00",
  },
  {
    train_id: "1833",
    ka_name: "COMMUTER LINE RANGKASBITUNG",
    route_name: "RANGKASBITUNG-SERPONG",
    dest: "SERPONG",
    time_est: "22:49:00",
    color: "#16812B",
    dest_time: "23:35:00",
  },
];

export async function GET() {
  const response = {
    status: 200,
    message: "Success",
    data: MJ,
  };

  return NextResponse.json(response); // Mengembalikan respons JSON
}
