import { NextResponse } from "next/server";

const YK = [
  {
    train_id: "676",
    ka_name: "COMMUTER LINE YK",
    route_name: "YOGYAKARTA-PALUR",
    dest: "PALUR",
    time_est: "05:30:00",
    color: "#E30A16",
    dest_time: "06:51:00",
  },
  {
    train_id: "551",
    ka_name: "PRAMBANAN EKSPRES",
    route_name: "YOGYAKARTA-KUTOARJO",
    dest: "KUTOARJO",
    time_est: "06:37:00",
    color: "#0084D8",
    dest_time: "07:44:00",
  },
  {
    train_id: "662",
    ka_name: "COMMUTER LINE YK",
    route_name: "YOGYAKARTA-PALUR",
    dest: "PALUR",
    time_est: "06:50:00",
    color: "#E30A16",
    dest_time: "08:15:00",
  },
  {
    train_id: "670A",
    ka_name: "COMMUTER LINE YK",
    route_name: "YOGYAKARTA-PALUR",
    dest: "PALUR",
    time_est: "07:40:00",
    color: "#E30A16",
    dest_time: "09:04:00",
  },
  {
    train_id: "678",
    ka_name: "COMMUTER LINE YK",
    route_name: "YOGYAKARTA-PALUR",
    dest: "PALUR",
    time_est: "08:50:00",
    color: "#E30A16",
    dest_time: "10:10:00",
  },
  {
    train_id: "664",
    ka_name: "COMMUTER LINE YK",
    route_name: "YOGYAKARTA-PALUR",
    dest: "PALUR",
    time_est: "10:25:00",
    color: "#E30A16",
    dest_time: "11:50:00",
  },
  {
    train_id: "553",
    ka_name: "PRAMBANAN EKSPRES",
    route_name: "YOGYAKARTA-KUTOARJO",
    dest: "KUTOARJO",
    time_est: "10:26:00",
    color: "#0084D8",
    dest_time: "11:47:00",
  },
  {
    train_id: "686F",
    ka_name: "COMMUTER LINE YK",
    route_name: "YOGYAKARTA-PALUR",
    dest: "PALUR",
    time_est: "10:56:00",
    color: "#E30A16",
    dest_time: "12:17:00",
  },
  {
    train_id: "672A",
    ka_name: "COMMUTER LINE YK",
    route_name: "YOGYAKARTA-PALUR",
    dest: "PALUR",
    time_est: "11:57:00",
    color: "#E30A16",
    dest_time: "13:18:00",
  },
  {
    train_id: "680",
    ka_name: "COMMUTER LINE YK",
    route_name: "YOGYAKARTA-PALUR",
    dest: "PALUR",
    time_est: "13:05:00",
    color: "#E30A16",
    dest_time: "14:40:00",
  },
  {
    train_id: "555",
    ka_name: "PRAMBANAN EKSPRES",
    route_name: "YOGYAKARTA-KUTOARJO",
    dest: "KUTOARJO",
    time_est: "13:49:00",
    color: "#0084D8",
    dest_time: "15:10:00",
  },
  {
    train_id: "688F",
    ka_name: "COMMUTER LINE YK",
    route_name: "YOGYAKARTA-PALUR",
    dest: "PALUR",
    time_est: "14:33:00",
    color: "#E30A16",
    dest_time: "15:53:00",
  },
  {
    train_id: "674",
    ka_name: "COMMUTER LINE YK",
    route_name: "YOGYAKARTA-PALUR",
    dest: "PALUR",
    time_est: "15:20:00",
    color: "#E30A16",
    dest_time: "16:41:00",
  },
  {
    train_id: "682A",
    ka_name: "COMMUTER LINE YK",
    route_name: "YOGYAKARTA-PALUR",
    dest: "PALUR",
    time_est: "16:30:00",
    color: "#E30A16",
    dest_time: "18:00:00",
  },
  {
    train_id: "561F",
    ka_name: "PRAMBANAN EKSPRES",
    route_name: "YOGYAKARTA-KUTOARJO",
    dest: "KUTOARJO",
    time_est: "16:38:00",
    color: "#0084D8",
    dest_time: "17:45:00",
  },
  {
    train_id: "668",
    ka_name: "COMMUTER LINE YK",
    route_name: "YOGYAKARTA-PALUR",
    dest: "PALUR",
    time_est: "17:45:00",
    color: "#E30A16",
    dest_time: "19:07:00",
  },
  {
    train_id: "557A",
    ka_name: "PRAMBANAN EKSPRES",
    route_name: "YOGYAKARTA-KUTOARJO",
    dest: "KUTOARJO",
    time_est: "17:50:00",
    color: "#0084D8",
    dest_time: "18:58:00",
  },
  {
    train_id: "690F",
    ka_name: "COMMUTER LINE YK",
    route_name: "YOGYAKARTA-PALUR",
    dest: "PALUR",
    time_est: "19:15:00",
    color: "#E30A16",
    dest_time: "20:38:00",
  },
  {
    train_id: "684",
    ka_name: "COMMUTER LINE YK",
    route_name: "YOGYAKARTA-PALUR",
    dest: "PALUR",
    time_est: "20:16:00",
    color: "#E30A16",
    dest_time: "21:38:00",
  },
  {
    train_id: "7102",
    ka_name: "COMMUTER LINE YK",
    route_name: "YOGYAKARTA-PALUR",
    dest: "PALUR",
    time_est: "22:35:00",
    color: "#E30A16",
    dest_time: "00:01:00",
  },
];

export async function GET() {
  const response = {
    status: 200,
    message: "Success",
    data: YK,
  };

  return NextResponse.json(response); // Mengembalikan respons JSON
}
