import { NextApiRequest, NextApiResponse } from 'next';

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  res.status(200).json({
    "status": 200,
    "data": [
      {
        "id": "AC",
        "name": "ANCOL",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "AK",
        "name": "ANGKE",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "BBN",
        "name": "BRAMBANAN",
        "daop": 6,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "BJD",
        "name": "BOJONGGEDE",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "BKS",
        "name": "BEKASI",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "BKST",
        "name": "BEKASITIMUR",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "BOI",
        "name": "BOJONGINDAH",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "BOO",
        "name": "BOGOR",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "BPR",
        "name": "BATUCEPER",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "BST",
        "name": "BANDARASOEKARNOHATTA",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "BUA",
        "name": "BUARAN",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "CBN",
        "name": "CIBINONG",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "CC",
        "name": "CICAYUR",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "CE",
        "name": "CEPER",
        "daop": 6,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "CIT",
        "name": "CIBITUNG",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "CJT",
        "name": "CILEJIT",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "CKI",
        "name": "CIKINI",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "CKR",
        "name": "CIKARANG",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "CKY",
        "name": "CIKOYA",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "CLT",
        "name": "CILEBUT",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "CSK",
        "name": "CISAUK",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "CTA",
        "name": "CITAYAM",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "CTR",
        "name": "CITERAS",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "CUK",
        "name": "CAKUNG",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "CW",
        "name": "CAWANG",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "DAR",
        "name": "DARU",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "DL",
        "name": "DELANGGU",
        "daop": 6,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "DP",
        "name": "DEPOK",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "DPB",
        "name": "DEPOKBARU",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "DRN",
        "name": "DURENKALIBATA",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "DU",
        "name": "DURI",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "GDD",
        "name": "GONDANGDIA",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "GGL",
        "name": "GROGOL",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "GST",
        "name": "GANGSENTIONG",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "GW",
        "name": "GAWOK",
        "daop": 6,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "JAKK",
        "name": "JAKARTAKOTA",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "JAY",
        "name": "JAYAKARTA",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "JMU",
        "name": "JURANGMANGU",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "JN",
        "name": "JENAR",
        "daop": 6,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "JNG",
        "name": "JATINEGARA",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "JUA",
        "name": "JUANDA",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "KAT",
        "name": "KARET",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "KBY",
        "name": "KEBAYORAN",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "KDS",
        "name": "KALIDERES",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "KLD",
        "name": "KLENDER",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "KLDB",
        "name": "KLENDERBARU",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "KMO",
        "name": "KEMAYORAN",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "KMT",
        "name": "KRAMAT",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "KPB",
        "name": "KAMPUNGBANDAN",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "KRI",
        "name": "KRANJI",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "KT",
        "name": "KLATEN",
        "daop": 6,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "KTA",
        "name": "KUTOARJO",
        "daop": 6,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "LNA",
        "name": "LENTENGAGUNG",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "LPN",
        "name": "LEMPUYANGAN",
        "daop": 6,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "MGB",
        "name": "MANGGABESAR",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "MGW",
        "name": "MAGUWO",
        "daop": 6,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "MJ",
        "name": "MAJA",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "MRI",
        "name": "MANGGARAI",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "MTR",
        "name": "MATRAMAN",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "NMO",
        "name": "NAMBO",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "PDJ",
        "name": "PONDOKRANJI",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "PI",
        "name": "PORIS",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "PL",
        "name": "PALUR",
        "daop": 6,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "PLM",
        "name": "PALMERAH",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "POC",
        "name": "PONDOKCINA",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "POK",
        "name": "PONDOKJATI",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "PRP",
        "name": "PARUNGPANJANG",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "PSE",
        "name": "PASARSENEN",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "PSG",
        "name": "PESING",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "PSM",
        "name": "PASARMINGGU",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "PSMB",
        "name": "PAS.MINGGUBARU",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "PWS",
        "name": "PURWOSARI",
        "daop": 6,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "RJW",
        "name": "RAJAWALI",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "RK",
        "name": "RANGKASBITUNG",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "RU",
        "name": "RAWABUNTU",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "RW",
        "name": "RAWABUAYA",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "SDM",
        "name": "SUDIMARA",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "SK",
        "name": "SOLO JEBRES",
        "daop": 6,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "SLO",
        "name": "SOLO BALAPAN",
        "daop": 6,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "SRP",
        "name": "SERPONG",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "SUD",
        "name": "SUDIRMAN",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "SUDB",
        "name": "SUDIRMAN BARU",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "SW",
        "name": "SAWAHBESAR",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "SWT",
        "name": "SROWOT",
        "daop": 6,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "TB",
        "name": "TAMBUN",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "TEB",
        "name": "TEBET",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "TEJ",
        "name": "TENJO",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "TGS",
        "name": "TIGARAKSA",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "THB",
        "name": "TANAHABANG",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "TKO",
        "name": "TAMANKOTA",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "TLM",
        "name": "M.TELAGAMURNI",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "TNG",
        "name": "TANGERANG",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "TNT",
        "name": "TANJUNGBARAT",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "TPK",
        "name": "TANJUNGPRIUK",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "TTI",
        "name": "TANAHTINGGI",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "UI",
        "name": "UNIV.INDONESIA",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "UP",
        "name": "UNIV.PANCASILA",
        "daop": 1,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "WJ",
        "name": "WOJO",
        "daop": 6,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "WT",
        "name": "WATES",
        "daop": 6,
        "fgEnable": 1,
        "haveSchedule": true,
      },
      {
        "id": "YK",
        "name": "YOGYAKARTA",
        "daop": 6,
        "fgEnable": 1,
        "haveSchedule": true,
      }
    ]
  });
}