import { NextResponse } from "next/server";

const JUA = [
  {
    train_id: "1303B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "00:00:00",
    color: "#E30A16",
    dest_time: "15:30:00",
  },
  {
    train_id: "1467B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "00:09:00",
    color: "#E30A16",
    dest_time: "00:20:00",
  },
  {
    train_id: "D1/R5501-6",
    ka_name: "DINAS RANGKAIAN KRL (TIDAK ANGKUT PENUMPANG)",
    route_name: "JAKARTAKOTA-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "04:47:00",
    color: "#E30A16",
    dest_time: "04:58:00",
  },
  {
    train_id: "1113B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "04:57:00",
    color: "#E30A16",
    dest_time: "05:09:00",
  },
  {
    train_id: "D1/R5016",
    ka_name: "DINAS RANGKAIAN KRL (TIDAK ANGKUT PENUMPANG)",
    route_name: "JAKARTAKOTA-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "04:58:00",
    color: "#E30A16",
    dest_time: "05:10:00",
  },
  {
    train_id: "1115B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "05:12:00",
    color: "#E30A16",
    dest_time: "05:25:00",
  },
  {
    train_id: "1119B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "05:25:00",
    color: "#E30A16",
    dest_time: "05:37:00",
  },
  {
    train_id: "1121B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "05:32:00",
    color: "#E30A16",
    dest_time: "05:45:00",
  },
  {
    train_id: "1504C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "05:35:00",
    color: "#E30A16",
    dest_time: "06:52:00",
  },
  {
    train_id: "1123B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "05:37:00",
    color: "#E30A16",
    dest_time: "05:49:00",
  },
  {
    train_id: "1114B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "05:42:00",
    color: "#E30A16",
    dest_time: "06:58:00",
  },
  {
    train_id: "1125B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "05:42:00",
    color: "#E30A16",
    dest_time: "05:53:00",
  },
  {
    train_id: "1127B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "05:47:00",
    color: "#E30A16",
    dest_time: "06:00:00",
  },
  {
    train_id: "1129B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "05:52:00",
    color: "#E30A16",
    dest_time: "06:05:00",
  },
  {
    train_id: "1118B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "05:54:00",
    color: "#E30A16",
    dest_time: "07:13:00",
  },
  {
    train_id: "1120B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:02:00",
    color: "#E30A16",
    dest_time: "07:18:00",
  },
  {
    train_id: "1131B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:04:00",
    color: "#E30A16",
    dest_time: "06:15:00",
  },
  {
    train_id: "1122B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:06:00",
    color: "#E30A16",
    dest_time: "07:23:00",
  },
  {
    train_id: "1133B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:09:00",
    color: "#E30A16",
    dest_time: "06:20:00",
  },
  {
    train_id: "1124B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:10:00",
    color: "#E30A16",
    dest_time: "07:27:00",
  },
  {
    train_id: "1135B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:15:00",
    color: "#E30A16",
    dest_time: "06:28:00",
  },
  {
    train_id: "1137B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:18:00",
    color: "#E30A16",
    dest_time: "06:32:00",
  },
  {
    train_id: "1126B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:20:00",
    color: "#E30A16",
    dest_time: "07:35:00",
  },
  {
    train_id: "1501C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "NAMBO-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:24:00",
    color: "#E30A16",
    dest_time: "06:36:00",
  },
  {
    train_id: "1128B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:28:00",
    color: "#E30A16",
    dest_time: "07:45:00",
  },
  {
    train_id: "1139B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:28:00",
    color: "#E30A16",
    dest_time: "06:41:00",
  },
  {
    train_id: "1130B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:33:00",
    color: "#E30A16",
    dest_time: "07:50:00",
  },
  {
    train_id: "1141B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOJONGGEDE-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:34:00",
    color: "#E30A16",
    dest_time: "06:47:00",
  },
  {
    train_id: "1143B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:40:00",
    color: "#E30A16",
    dest_time: "06:53:00",
  },
  {
    train_id: "1132B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:41:00",
    color: "#E30A16",
    dest_time: "07:57:00",
  },
  {
    train_id: "1134B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:46:00",
    color: "#E30A16",
    dest_time: "08:03:00",
  },
  {
    train_id: "1136B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:52:00",
    color: "#E30A16",
    dest_time: "08:08:00",
  },
  {
    train_id: "1147B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:53:00",
    color: "#E30A16",
    dest_time: "07:05:00",
  },
  {
    train_id: "1149B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOJONGGEDE-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:58:00",
    color: "#E30A16",
    dest_time: "07:10:00",
  },
  {
    train_id: "1506C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "06:59:00",
    color: "#E30A16",
    dest_time: "08:16:00",
  },
  {
    train_id: "1151B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:04:00",
    color: "#E30A16",
    dest_time: "07:17:00",
  },
  {
    train_id: "1138B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "07:06:00",
    color: "#E30A16",
    dest_time: "08:22:00",
  },
  {
    train_id: "1140C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "07:10:00",
    color: "#E30A16",
    dest_time: "08:00:00",
  },
  {
    train_id: "1153B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:12:00",
    color: "#E30A16",
    dest_time: "07:24:00",
  },
  {
    train_id: "1142B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "07:15:00",
    color: "#E30A16",
    dest_time: "08:33:00",
  },
  {
    train_id: "1155B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:19:00",
    color: "#E30A16",
    dest_time: "07:32:00",
  },
  {
    train_id: "1146D",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "07:21:00",
    color: "#E30A16",
    dest_time: "08:12:00",
  },
  {
    train_id: "1503C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "NAMBO-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:24:00",
    color: "#E30A16",
    dest_time: "07:36:00",
  },
  {
    train_id: "1157B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:29:00",
    color: "#E30A16",
    dest_time: "07:41:00",
  },
  {
    train_id: "1159B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:34:00",
    color: "#E30A16",
    dest_time: "07:45:00",
  },
  {
    train_id: "1148B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "07:37:00",
    color: "#E30A16",
    dest_time: "08:54:00",
  },
  {
    train_id: "1161B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:38:00",
    color: "#E30A16",
    dest_time: "07:49:00",
  },
  {
    train_id: "1150B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "07:41:00",
    color: "#E30A16",
    dest_time: "08:59:00",
  },
  {
    train_id: "1152B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "07:46:00",
    color: "#E30A16",
    dest_time: "09:04:00",
  },
  {
    train_id: "1163B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:47:00",
    color: "#E30A16",
    dest_time: "08:00:00",
  },
  {
    train_id: "1154B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "07:50:00",
    color: "#E30A16",
    dest_time: "09:08:00",
  },
  {
    train_id: "1165B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:53:00",
    color: "#E30A16",
    dest_time: "08:04:00",
  },
  {
    train_id: "1156B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "07:54:00",
    color: "#E30A16",
    dest_time: "09:13:00",
  },
  {
    train_id: "1167B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:57:00",
    color: "#E30A16",
    dest_time: "08:11:00",
  },
  {
    train_id: "1158B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "07:59:00",
    color: "#E30A16",
    dest_time: "08:56:00",
  },
  {
    train_id: "1169B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:01:00",
    color: "#E30A16",
    dest_time: "08:16:00",
  },
  {
    train_id: "1160B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "08:09:00",
    color: "#E30A16",
    dest_time: "09:28:00",
  },
  {
    train_id: "1171B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:15:00",
    color: "#E30A16",
    dest_time: "08:26:00",
  },
  {
    train_id: "1162B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "08:16:00",
    color: "#E30A16",
    dest_time: "09:34:00",
  },
  {
    train_id: "1505C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "NAMBO-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:18:00",
    color: "#E30A16",
    dest_time: "08:30:00",
  },
  {
    train_id: "1164B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "08:25:00",
    color: "#E30A16",
    dest_time: "09:45:00",
  },
  {
    train_id: "1173B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:25:00",
    color: "#E30A16",
    dest_time: "08:38:00",
  },
  {
    train_id: "1175B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:29:00",
    color: "#E30A16",
    dest_time: "08:42:00",
  },
  {
    train_id: "1166B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "08:30:00",
    color: "#E30A16",
    dest_time: "09:49:00",
  },
  {
    train_id: "1177B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:34:00",
    color: "#E30A16",
    dest_time: "08:47:00",
  },
  {
    train_id: "1168B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "08:39:00",
    color: "#E30A16",
    dest_time: "09:54:00",
  },
  {
    train_id: "D1/R1169B-2",
    ka_name: "DINAS RANGKAIAN KRL (TIDAK ANGKUT PENUMPANG)",
    route_name: "JAKARTAKOTA-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "08:42:00",
    color: "#E30A16",
    dest_time: "08:56:00",
  },
  {
    train_id: "1179B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:43:00",
    color: "#E30A16",
    dest_time: "08:58:00",
  },
  {
    train_id: "1508C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "08:49:00",
    color: "#E30A16",
    dest_time: "10:10:00",
  },
  {
    train_id: "1181B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:50:00",
    color: "#E30A16",
    dest_time: "09:03:00",
  },
  {
    train_id: "1172B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "08:52:00",
    color: "#E30A16",
    dest_time: "10:14:00",
  },
  {
    train_id: "1183B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:54:00",
    color: "#E30A16",
    dest_time: "09:07:00",
  },
  {
    train_id: "1174C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "08:59:00",
    color: "#E30A16",
    dest_time: "09:52:00",
  },
  {
    train_id: "1185B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:03:00",
    color: "#E30A16",
    dest_time: "09:16:00",
  },
  {
    train_id: "1176B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "09:08:00",
    color: "#E30A16",
    dest_time: "10:24:00",
  },
  {
    train_id: "1187B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:09:00",
    color: "#E30A16",
    dest_time: "09:21:00",
  },
  {
    train_id: "1178B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "09:12:00",
    color: "#E30A16",
    dest_time: "10:29:00",
  },
  {
    train_id: "1189B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:13:00",
    color: "#E30A16",
    dest_time: "09:26:00",
  },
  {
    train_id: "1180B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "09:17:00",
    color: "#E30A16",
    dest_time: "10:33:00",
  },
  {
    train_id: "1191B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:18:00",
    color: "#E30A16",
    dest_time: "09:30:00",
  },
  {
    train_id: "1182C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "09:21:00",
    color: "#E30A16",
    dest_time: "10:11:00",
  },
  {
    train_id: "1193B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:22:00",
    color: "#E30A16",
    dest_time: "09:35:00",
  },
  {
    train_id: "1195B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:28:00",
    color: "#E30A16",
    dest_time: "09:40:00",
  },
  {
    train_id: "1197B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:30:00",
    color: "#E30A16",
    dest_time: "09:44:00",
  },
  {
    train_id: "1184B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "09:35:00",
    color: "#E30A16",
    dest_time: "10:49:00",
  },
  {
    train_id: "1186C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "09:38:00",
    color: "#E30A16",
    dest_time: "10:54:00",
  },
  {
    train_id: "1199B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:44:00",
    color: "#E30A16",
    dest_time: "09:56:00",
  },
  {
    train_id: "1188C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "09:45:00",
    color: "#E30A16",
    dest_time: "10:37:00",
  },
  {
    train_id: "1190B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "09:49:00",
    color: "#E30A16",
    dest_time: "11:09:00",
  },
  {
    train_id: "1507C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "NAMBO-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:50:00",
    color: "#E30A16",
    dest_time: "10:02:00",
  },
  {
    train_id: "1192C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "09:56:00",
    color: "#E30A16",
    dest_time: "10:47:00",
  },
  {
    train_id: "1201B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:58:00",
    color: "#E30A16",
    dest_time: "10:10:00",
  },
  {
    train_id: "1194B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "10:00:00",
    color: "#E30A16",
    dest_time: "11:24:00",
  },
  {
    train_id: "1203B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:03:00",
    color: "#E30A16",
    dest_time: "10:15:00",
  },
  {
    train_id: "1196B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "10:07:00",
    color: "#E30A16",
    dest_time: "11:29:00",
  },
  {
    train_id: "1207B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:18:00",
    color: "#E30A16",
    dest_time: "10:29:00",
  },
  {
    train_id: "1198B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "10:19:00",
    color: "#E30A16",
    dest_time: "11:34:00",
  },
  {
    train_id: "1200B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "10:23:00",
    color: "#E30A16",
    dest_time: "11:39:00",
  },
  {
    train_id: "1202B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "10:28:00",
    color: "#E30A16",
    dest_time: "11:17:00",
  },
  {
    train_id: "1211B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:28:00",
    color: "#E30A16",
    dest_time: "10:39:00",
  },
  {
    train_id: "1213B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:33:00",
    color: "#E30A16",
    dest_time: "10:44:00",
  },
  {
    train_id: "1510C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "10:34:00",
    color: "#E30A16",
    dest_time: "11:50:00",
  },
  {
    train_id: "1204B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "10:39:00",
    color: "#E30A16",
    dest_time: "11:54:00",
  },
  {
    train_id: "1215B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:40:00",
    color: "#E30A16",
    dest_time: "10:51:00",
  },
  {
    train_id: "1208B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "10:49:00",
    color: "#E30A16",
    dest_time: "12:04:00",
  },
  {
    train_id: "1219B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:49:00",
    color: "#E30A16",
    dest_time: "11:00:00",
  },
  {
    train_id: "1223B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:59:00",
    color: "#E30A16",
    dest_time: "11:10:00",
  },
  {
    train_id: "1212B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "11:04:00",
    color: "#E30A16",
    dest_time: "12:19:00",
  },
  {
    train_id: "D1/R1213B-2",
    ka_name: "DINAS RANGKAIAN KRL (TIDAK ANGKUT PENUMPANG)",
    route_name: "JAKARTAKOTA-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "11:08:00",
    color: "#E30A16",
    dest_time: "11:23:00",
  },
  {
    train_id: "1227B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:13:00",
    color: "#E30A16",
    dest_time: "11:24:00",
  },
  {
    train_id: "1216B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "11:14:00",
    color: "#E30A16",
    dest_time: "12:29:00",
  },
  {
    train_id: "1229B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:18:00",
    color: "#E30A16",
    dest_time: "11:29:00",
  },
  {
    train_id: "1220B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "11:22:00",
    color: "#E30A16",
    dest_time: "12:13:00",
  },
  {
    train_id: "1233B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:28:00",
    color: "#E30A16",
    dest_time: "11:39:00",
  },
  {
    train_id: "1224B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "11:33:00",
    color: "#E30A16",
    dest_time: "12:48:00",
  },
  {
    train_id: "1509C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "NAMBO-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:33:00",
    color: "#E30A16",
    dest_time: "11:44:00",
  },
  {
    train_id: "1235B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:37:00",
    color: "#E30A16",
    dest_time: "11:48:00",
  },
  {
    train_id: "1228B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "11:48:00",
    color: "#E30A16",
    dest_time: "13:03:00",
  },
  {
    train_id: "1239B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:50:00",
    color: "#E30A16",
    dest_time: "12:04:00",
  },
  {
    train_id: "1230B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "11:53:00",
    color: "#E30A16",
    dest_time: "13:09:00",
  },
  {
    train_id: "1241B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:59:00",
    color: "#E30A16",
    dest_time: "12:10:00",
  },
  {
    train_id: "1512C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "12:03:00",
    color: "#E30A16",
    dest_time: "13:22:00",
  },
  {
    train_id: "1234B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "12:09:00",
    color: "#E30A16",
    dest_time: "13:28:00",
  },
  {
    train_id: "1245B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "12:14:00",
    color: "#E30A16",
    dest_time: "12:24:00",
  },
  {
    train_id: "1236B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "12:15:00",
    color: "#E30A16",
    dest_time: "13:33:00",
  },
  {
    train_id: "1249B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "12:24:00",
    color: "#E30A16",
    dest_time: "12:34:00",
  },
  {
    train_id: "1240B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "12:29:00",
    color: "#E30A16",
    dest_time: "13:44:00",
  },
  {
    train_id: "1242B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "12:33:00",
    color: "#E30A16",
    dest_time: "13:53:00",
  },
  {
    train_id: "1253B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "12:34:00",
    color: "#E30A16",
    dest_time: "12:45:00",
  },
  {
    train_id: "1246B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "12:49:00",
    color: "#E30A16",
    dest_time: "14:04:00",
  },
  {
    train_id: "1257B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "12:49:00",
    color: "#E30A16",
    dest_time: "12:59:00",
  },
  {
    train_id: "1261B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "12:58:00",
    color: "#E30A16",
    dest_time: "13:09:00",
  },
  {
    train_id: "1250B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "12:59:00",
    color: "#E30A16",
    dest_time: "14:14:00",
  },
  {
    train_id: "1263B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "13:03:00",
    color: "#E30A16",
    dest_time: "13:14:00",
  },
  {
    train_id: "1254B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "13:08:00",
    color: "#E30A16",
    dest_time: "14:24:00",
  },
  {
    train_id: "1265B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "13:08:00",
    color: "#E30A16",
    dest_time: "13:19:00",
  },
  {
    train_id: "1511C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "NAMBO-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "13:13:00",
    color: "#E30A16",
    dest_time: "13:24:00",
  },
  {
    train_id: "1267B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "13:17:00",
    color: "#E30A16",
    dest_time: "13:28:00",
  },
  {
    train_id: "1258B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "13:24:00",
    color: "#E30A16",
    dest_time: "14:39:00",
  },
  {
    train_id: "1262B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "13:33:00",
    color: "#E30A16",
    dest_time: "14:49:00",
  },
  {
    train_id: "1271B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "13:33:00",
    color: "#E30A16",
    dest_time: "13:46:00",
  },
  {
    train_id: "1264B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "13:38:00",
    color: "#E30A16",
    dest_time: "14:54:00",
  },
  {
    train_id: "1266B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "13:42:00",
    color: "#E30A16",
    dest_time: "14:59:00",
  },
  {
    train_id: "1275B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "13:43:00",
    color: "#E30A16",
    dest_time: "13:54:00",
  },
  {
    train_id: "1514C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "13:46:00",
    color: "#E30A16",
    dest_time: "15:04:00",
  },
  {
    train_id: "1268B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "13:51:00",
    color: "#E30A16",
    dest_time: "15:09:00",
  },
  {
    train_id: "1279B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "13:54:00",
    color: "#E30A16",
    dest_time: "14:05:00",
  },
  {
    train_id: "1272B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "14:08:00",
    color: "#E30A16",
    dest_time: "15:24:00",
  },
  {
    train_id: "1276B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "14:18:00",
    color: "#E30A16",
    dest_time: "15:35:00",
  },
  {
    train_id: "1285B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:18:00",
    color: "#E30A16",
    dest_time: "14:30:00",
  },
  {
    train_id: "1289B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:28:00",
    color: "#E30A16",
    dest_time: "14:39:00",
  },
  {
    train_id: "1280B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "14:29:00",
    color: "#E30A16",
    dest_time: "15:44:00",
  },
  {
    train_id: "1291B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:33:00",
    color: "#E30A16",
    dest_time: "14:44:00",
  },
  {
    train_id: "1513C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "NAMBO-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:48:00",
    color: "#E30A16",
    dest_time: "14:59:00",
  },
  {
    train_id: "1295B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:53:00",
    color: "#E30A16",
    dest_time: "15:04:00",
  },
  {
    train_id: "1286B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "14:54:00",
    color: "#E30A16",
    dest_time: "16:10:00",
  },
  {
    train_id: "1297B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:57:00",
    color: "#E30A16",
    dest_time: "15:08:00",
  },
  {
    train_id: "1299C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:02:00",
    color: "#E30A16",
    dest_time: "15:13:00",
  },
  {
    train_id: "1290B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "15:03:00",
    color: "#E30A16",
    dest_time: "16:19:00",
  },
  {
    train_id: "1292B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "15:08:00",
    color: "#E30A16",
    dest_time: "16:24:00",
  },
  {
    train_id: "1301B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:14:00",
    color: "#E30A16",
    dest_time: "15:25:00",
  },
  {
    train_id: "1296B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "15:22:00",
    color: "#E30A16",
    dest_time: "16:37:00",
  },
  {
    train_id: "1305C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:24:00",
    color: "#E30A16",
    dest_time: "15:37:00",
  },
  {
    train_id: "1298B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "15:26:00",
    color: "#E30A16",
    dest_time: "16:41:00",
  },
  {
    train_id: "1307B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:28:00",
    color: "#E30A16",
    dest_time: "15:41:00",
  },
  {
    train_id: "1516C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "15:30:00",
    color: "#E30A16",
    dest_time: "16:50:00",
  },
  {
    train_id: "1300B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "15:38:00",
    color: "#E30A16",
    dest_time: "16:53:00",
  },
  {
    train_id: "1302B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "15:42:00",
    color: "#E30A16",
    dest_time: "16:57:00",
  },
  {
    train_id: "1304B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "15:48:00",
    color: "#E30A16",
    dest_time: "17:04:00",
  },
  {
    train_id: "1313B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:48:00",
    color: "#E30A16",
    dest_time: "16:00:00",
  },
  {
    train_id: "1315B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:53:00",
    color: "#E30A16",
    dest_time: "16:04:00",
  },
  {
    train_id: "1306B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "15:55:00",
    color: "#E30A16",
    dest_time: "17:14:00",
  },
  {
    train_id: "1317C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:58:00",
    color: "#E30A16",
    dest_time: "16:10:00",
  },
  {
    train_id: "1308B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:00:00",
    color: "#E30A16",
    dest_time: "17:18:00",
  },
  {
    train_id: "1319B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:04:00",
    color: "#E30A16",
    dest_time: "16:18:00",
  },
  {
    train_id: "1321B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:13:00",
    color: "#E30A16",
    dest_time: "16:26:00",
  },
  {
    train_id: "1323B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:17:00",
    color: "#E30A16",
    dest_time: "16:30:00",
  },
  {
    train_id: "1314B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:19:00",
    color: "#E30A16",
    dest_time: "17:34:00",
  },
  {
    train_id: "1325B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:23:00",
    color: "#E30A16",
    dest_time: "16:38:00",
  },
  {
    train_id: "1316B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:27:00",
    color: "#E30A16",
    dest_time: "17:42:00",
  },
  {
    train_id: "1515C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "NAMBO-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:29:00",
    color: "#E30A16",
    dest_time: "16:42:00",
  },
  {
    train_id: "1318B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:31:00",
    color: "#E30A16",
    dest_time: "17:46:00",
  },
  {
    train_id: "1327B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:32:00",
    color: "#E30A16",
    dest_time: "16:46:00",
  },
  {
    train_id: "1320B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:39:00",
    color: "#E30A16",
    dest_time: "17:55:00",
  },
  {
    train_id: "1329B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:39:00",
    color: "#E30A16",
    dest_time: "16:51:00",
  },
  {
    train_id: "1322B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:43:00",
    color: "#E30A16",
    dest_time: "17:59:00",
  },
  {
    train_id: "1324B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:47:00",
    color: "#E30A16",
    dest_time: "18:04:00",
  },
  {
    train_id: "1331C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:47:00",
    color: "#E30A16",
    dest_time: "17:00:00",
  },
  {
    train_id: "D1/R1334B-1",
    ka_name: "DINAS RANGKAIAN KRL (TIDAK ANGKUT PENUMPANG)",
    route_name: "MANGGARAI-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:53:00",
    color: "#E30A16",
    dest_time: "17:05:00",
  },
  {
    train_id: "1326B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:57:00",
    color: "#E30A16",
    dest_time: "18:15:00",
  },
  {
    train_id: "1335B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:57:00",
    color: "#E30A16",
    dest_time: "17:09:00",
  },
  {
    train_id: "1328B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:01:00",
    color: "#E30A16",
    dest_time: "18:19:00",
  },
  {
    train_id: "D1/R1338B-1",
    ka_name: "DINAS RANGKAIAN KRL (TIDAK ANGKUT PENUMPANG)",
    route_name: "MANGGARAI-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:03:00",
    color: "#E30A16",
    dest_time: "17:14:00",
  },
  {
    train_id: "1330B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:05:00",
    color: "#E30A16",
    dest_time: "18:23:00",
  },
  {
    train_id: "1339B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:06:00",
    color: "#E30A16",
    dest_time: "17:18:00",
  },
  {
    train_id: "1518C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "17:11:00",
    color: "#E30A16",
    dest_time: "18:30:00",
  },
  {
    train_id: "1332B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:19:00",
    color: "#E30A16",
    dest_time: "18:34:00",
  },
  {
    train_id: "1341B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:19:00",
    color: "#E30A16",
    dest_time: "17:30:00",
  },
  {
    train_id: "1334B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:23:00",
    color: "#E30A16",
    dest_time: "18:38:00",
  },
  {
    train_id: "1343B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:25:00",
    color: "#E30A16",
    dest_time: "17:38:00",
  },
  {
    train_id: "1345B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:29:00",
    color: "#E30A16",
    dest_time: "17:42:00",
  },
  {
    train_id: "1336B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:31:00",
    color: "#E30A16",
    dest_time: "18:48:00",
  },
  {
    train_id: "1347B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:32:00",
    color: "#E30A16",
    dest_time: "17:46:00",
  },
  {
    train_id: "1338B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:35:00",
    color: "#E30A16",
    dest_time: "18:53:00",
  },
  {
    train_id: "1340B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:39:00",
    color: "#E30A16",
    dest_time: "18:58:00",
  },
  {
    train_id: "1349C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:42:00",
    color: "#E30A16",
    dest_time: "17:55:00",
  },
  {
    train_id: "1342B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:46:00",
    color: "#E30A16",
    dest_time: "19:03:00",
  },
  {
    train_id: "1351B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:49:00",
    color: "#E30A16",
    dest_time: "18:02:00",
  },
  {
    train_id: "1353C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:54:00",
    color: "#E30A16",
    dest_time: "18:08:00",
  },
  {
    train_id: "1344B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:55:00",
    color: "#E30A16",
    dest_time: "19:12:00",
  },
  {
    train_id: "1346B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:00:00",
    color: "#E30A16",
    dest_time: "19:16:00",
  },
  {
    train_id: "1355B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:00:00",
    color: "#E30A16",
    dest_time: "18:14:00",
  },
  {
    train_id: "1348B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:07:00",
    color: "#E30A16",
    dest_time: "19:24:00",
  },
  {
    train_id: "1357B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:09:00",
    color: "#E30A16",
    dest_time: "18:20:00",
  },
  {
    train_id: "1350B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:13:00",
    color: "#E30A16",
    dest_time: "19:29:00",
  },
  {
    train_id: "1359B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:16:00",
    color: "#E30A16",
    dest_time: "18:28:00",
  },
  {
    train_id: "1352B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:19:00",
    color: "#E30A16",
    dest_time: "19:38:00",
  },
  {
    train_id: "1517C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "NAMBO-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:24:00",
    color: "#E30A16",
    dest_time: "18:35:00",
  },
  {
    train_id: "1361B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:28:00",
    color: "#E30A16",
    dest_time: "18:39:00",
  },
  {
    train_id: "1354B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:29:00",
    color: "#E30A16",
    dest_time: "19:43:00",
  },
  {
    train_id: "1356B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:33:00",
    color: "#E30A16",
    dest_time: "19:48:00",
  },
  {
    train_id: "1358B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:38:00",
    color: "#E30A16",
    dest_time: "19:53:00",
  },
  {
    train_id: "1365B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:39:00",
    color: "#E30A16",
    dest_time: "18:52:00",
  },
  {
    train_id: "1367B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:45:00",
    color: "#E30A16",
    dest_time: "18:58:00",
  },
  {
    train_id: "1360B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:48:00",
    color: "#E30A16",
    dest_time: "20:03:00",
  },
  {
    train_id: "1520C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "18:52:00",
    color: "#E30A16",
    dest_time: "20:07:00",
  },
  {
    train_id: "1362B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:56:00",
    color: "#E30A16",
    dest_time: "20:13:00",
  },
  {
    train_id: "1371B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:00:00",
    color: "#E30A16",
    dest_time: "19:12:00",
  },
  {
    train_id: "1373B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:04:00",
    color: "#E30A16",
    dest_time: "19:16:00",
  },
  {
    train_id: "1366B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "19:08:00",
    color: "#E30A16",
    dest_time: "20:25:00",
  },
  {
    train_id: "1375B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:11:00",
    color: "#E30A16",
    dest_time: "19:23:00",
  },
  {
    train_id: "1377B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:15:00",
    color: "#E30A16",
    dest_time: "19:27:00",
  },
  {
    train_id: "1368B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "19:17:00",
    color: "#E30A16",
    dest_time: "20:34:00",
  },
  {
    train_id: "1379B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:19:00",
    color: "#E30A16",
    dest_time: "19:31:00",
  },
  {
    train_id: "1372B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "19:28:00",
    color: "#E30A16",
    dest_time: "20:44:00",
  },
  {
    train_id: "1383B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:33:00",
    color: "#E30A16",
    dest_time: "19:45:00",
  },
  {
    train_id: "1374B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "19:35:00",
    color: "#E30A16",
    dest_time: "20:49:00",
  },
  {
    train_id: "1385B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:37:00",
    color: "#E30A16",
    dest_time: "19:49:00",
  },
  {
    train_id: "1376B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "19:42:00",
    color: "#E30A16",
    dest_time: "20:59:00",
  },
  {
    train_id: "1387B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:44:00",
    color: "#E30A16",
    dest_time: "19:57:00",
  },
  {
    train_id: "1378B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "19:46:00",
    color: "#E30A16",
    dest_time: "21:04:00",
  },
  {
    train_id: "1519C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "NAMBO-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:53:00",
    color: "#E30A16",
    dest_time: "20:05:00",
  },
  {
    train_id: "1380B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "19:54:00",
    color: "#E30A16",
    dest_time: "21:09:00",
  },
  {
    train_id: "1389B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:58:00",
    color: "#E30A16",
    dest_time: "20:09:00",
  },
  {
    train_id: "1391B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "20:04:00",
    color: "#E30A16",
    dest_time: "20:15:00",
  },
  {
    train_id: "1384B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "20:06:00",
    color: "#E30A16",
    dest_time: "21:21:00",
  },
  {
    train_id: "1386B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "20:10:00",
    color: "#E30A16",
    dest_time: "21:25:00",
  },
  {
    train_id: "1393B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "20:10:00",
    color: "#E30A16",
    dest_time: "20:23:00",
  },
  {
    train_id: "1388B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "20:14:00",
    color: "#E30A16",
    dest_time: "21:29:00",
  },
  {
    train_id: "1395B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "20:15:00",
    color: "#E30A16",
    dest_time: "20:27:00",
  },
  {
    train_id: "1397B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "20:19:00",
    color: "#E30A16",
    dest_time: "20:31:00",
  },
  {
    train_id: "1390C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "20:22:00",
    color: "#E30A16",
    dest_time: "21:12:00",
  },
  {
    train_id: "1392B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "20:28:00",
    color: "#E30A16",
    dest_time: "21:43:00",
  },
  {
    train_id: "1522C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "20:32:00",
    color: "#E30A16",
    dest_time: "21:49:00",
  },
  {
    train_id: "1401B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "20:34:00",
    color: "#E30A16",
    dest_time: "20:45:00",
  },
  {
    train_id: "1403B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "20:38:00",
    color: "#E30A16",
    dest_time: "20:49:00",
  },
  {
    train_id: "1394B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "20:43:00",
    color: "#E30A16",
    dest_time: "21:58:00",
  },
  {
    train_id: "1396B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "20:49:00",
    color: "#E30A16",
    dest_time: "22:04:00",
  },
  {
    train_id: "1407B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "20:53:00",
    color: "#E30A16",
    dest_time: "21:04:00",
  },
  {
    train_id: "1398B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "20:54:00",
    color: "#E30A16",
    dest_time: "22:09:00",
  },
  {
    train_id: "1402B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "21:08:00",
    color: "#E30A16",
    dest_time: "22:25:00",
  },
  {
    train_id: "1411B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "21:13:00",
    color: "#E30A16",
    dest_time: "21:25:00",
  },
  {
    train_id: "1404B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "21:14:00",
    color: "#E30A16",
    dest_time: "22:29:00",
  },
  {
    train_id: "1415B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "21:23:00",
    color: "#E30A16",
    dest_time: "21:34:00",
  },
  {
    train_id: "1408B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "21:29:00",
    color: "#E30A16",
    dest_time: "22:44:00",
  },
  {
    train_id: "1419B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "21:38:00",
    color: "#E30A16",
    dest_time: "21:49:00",
  },
  {
    train_id: "1521C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "NAMBO-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "21:43:00",
    color: "#E30A16",
    dest_time: "21:54:00",
  },
  {
    train_id: "1412B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "21:44:00",
    color: "#E30A16",
    dest_time: "22:59:00",
  },
  {
    train_id: "1414B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "21:53:00",
    color: "#E30A16",
    dest_time: "23:08:00",
  },
  {
    train_id: "1423B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "21:53:00",
    color: "#E30A16",
    dest_time: "22:05:00",
  },
  {
    train_id: "1425B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "22:05:00",
    color: "#E30A16",
    dest_time: "22:16:00",
  },
  {
    train_id: "1418B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "22:06:00",
    color: "#E30A16",
    dest_time: "23:21:00",
  },
  {
    train_id: "1420B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "22:13:00",
    color: "#E30A16",
    dest_time: "23:28:00",
  },
  {
    train_id: "1431B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "22:19:00",
    color: "#E30A16",
    dest_time: "22:30:00",
  },
  {
    train_id: "1424B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "22:21:00",
    color: "#E30A16",
    dest_time: "23:36:00",
  },
  {
    train_id: "1433B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "22:23:00",
    color: "#E30A16",
    dest_time: "22:34:00",
  },
  {
    train_id: "1426B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "22:32:00",
    color: "#E30A16",
    dest_time: "23:47:00",
  },
  {
    train_id: "1437B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "22:35:00",
    color: "#E30A16",
    dest_time: "22:46:00",
  },
  {
    train_id: "1432B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "22:48:00",
    color: "#E30A16",
    dest_time: "00:03:00",
  },
  {
    train_id: "1443B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "22:53:00",
    color: "#E30A16",
    dest_time: "23:04:00",
  },
  {
    train_id: "1434B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "22:58:00",
    color: "#E30A16",
    dest_time: "00:12:00",
  },
];

export async function GET() {
  const response = {
    status: 200,
    message: "Success",
    data: JUA,
  };

  return NextResponse.json(response); // Mengembalikan respons JSON
}
