import { NextResponse } from "next/server";

const CW = [
  {
    train_id: "1448B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "00:05:00",
    color: "#E30A16",
    dest_time: "00:34:00",
  },
  {
    train_id: "1452B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "00:20:00",
    color: "#E30A16",
    dest_time: "01:17:00",
  },
  {
    train_id: "1000B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "04:37:00",
    color: "#E30A16",
    dest_time: "05:34:00",
  },
  {
    train_id: "1113B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "04:37:00",
    color: "#E30A16",
    dest_time: "05:09:00",
  },
  {
    train_id: "1115B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "04:54:00",
    color: "#E30A16",
    dest_time: "05:25:00",
  },
  {
    train_id: "1119B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "05:04:00",
    color: "#E30A16",
    dest_time: "05:37:00",
  },
  {
    train_id: "1121B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "05:14:00",
    color: "#E30A16",
    dest_time: "05:45:00",
  },
  {
    train_id: "1123B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "05:19:00",
    color: "#E30A16",
    dest_time: "05:49:00",
  },
  {
    train_id: "1125B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "05:24:00",
    color: "#E30A16",
    dest_time: "05:53:00",
  },
  {
    train_id: "1127B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "05:29:00",
    color: "#E30A16",
    dest_time: "06:00:00",
  },
  {
    train_id: "1129B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "05:34:00",
    color: "#E30A16",
    dest_time: "06:05:00",
  },
  {
    train_id: "1333D",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "05:40:00",
    color: "#E30A16",
    dest_time: "05:47:00",
  },
  {
    train_id: "1131B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "05:44:00",
    color: "#E30A16",
    dest_time: "06:15:00",
  },
  {
    train_id: "1133B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "05:49:00",
    color: "#E30A16",
    dest_time: "06:20:00",
  },
  {
    train_id: "1504C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "05:53:00",
    color: "#E30A16",
    dest_time: "06:52:00",
  },
  {
    train_id: "1135B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "05:54:00",
    color: "#E30A16",
    dest_time: "06:28:00",
  },
  {
    train_id: "1137B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "05:59:00",
    color: "#E30A16",
    dest_time: "06:32:00",
  },
  {
    train_id: "1114B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:01:00",
    color: "#E30A16",
    dest_time: "06:58:00",
  },
  {
    train_id: "1501C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "NAMBO-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:05:00",
    color: "#E30A16",
    dest_time: "06:36:00",
  },
  {
    train_id: "1139B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:09:00",
    color: "#E30A16",
    dest_time: "06:41:00",
  },
  {
    train_id: "1170C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "06:11:00",
    color: "#E30A16",
    dest_time: "07:08:00",
  },
  {
    train_id: "1141B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOJONGGEDE-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:14:00",
    color: "#E30A16",
    dest_time: "06:47:00",
  },
  {
    train_id: "1118B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:16:00",
    color: "#E30A16",
    dest_time: "07:13:00",
  },
  {
    train_id: "1143B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:19:00",
    color: "#E30A16",
    dest_time: "06:53:00",
  },
  {
    train_id: "1120B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:21:00",
    color: "#E30A16",
    dest_time: "07:18:00",
  },
  {
    train_id: "1007B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "06:24:00",
    color: "#E30A16",
    dest_time: "06:31:00",
  },
  {
    train_id: "1122B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:25:00",
    color: "#E30A16",
    dest_time: "07:23:00",
  },
  {
    train_id: "1124B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:29:00",
    color: "#E30A16",
    dest_time: "07:27:00",
  },
  {
    train_id: "1147B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:35:00",
    color: "#E30A16",
    dest_time: "07:05:00",
  },
  {
    train_id: "1126B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:38:00",
    color: "#E30A16",
    dest_time: "07:35:00",
  },
  {
    train_id: "1149B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOJONGGEDE-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:40:00",
    color: "#E30A16",
    dest_time: "07:10:00",
  },
  {
    train_id: "1008B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "06:43:00",
    color: "#E30A16",
    dest_time: "07:40:00",
  },
  {
    train_id: "1151B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:45:00",
    color: "#E30A16",
    dest_time: "07:17:00",
  },
  {
    train_id: "1128B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:46:00",
    color: "#E30A16",
    dest_time: "07:45:00",
  },
  {
    train_id: "1009B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "06:50:00",
    color: "#E30A16",
    dest_time: "06:58:00",
  },
  {
    train_id: "1130B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:52:00",
    color: "#E30A16",
    dest_time: "07:50:00",
  },
  {
    train_id: "1153B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:55:00",
    color: "#E30A16",
    dest_time: "07:24:00",
  },
  {
    train_id: "1132B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:58:00",
    color: "#E30A16",
    dest_time: "07:57:00",
  },
  {
    train_id: "1155B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:59:00",
    color: "#E30A16",
    dest_time: "07:32:00",
  },
  {
    train_id: "1134B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "07:05:00",
    color: "#E30A16",
    dest_time: "08:03:00",
  },
  {
    train_id: "1503C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "NAMBO-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:05:00",
    color: "#E30A16",
    dest_time: "07:36:00",
  },
  {
    train_id: "1157B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:09:00",
    color: "#E30A16",
    dest_time: "07:41:00",
  },
  {
    train_id: "1136B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "07:10:00",
    color: "#E30A16",
    dest_time: "08:08:00",
  },
  {
    train_id: "1010B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "07:14:00",
    color: "#E30A16",
    dest_time: "08:12:00",
  },
  {
    train_id: "1159B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:14:00",
    color: "#E30A16",
    dest_time: "07:45:00",
  },
  {
    train_id: "1506C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "07:18:00",
    color: "#E30A16",
    dest_time: "08:16:00",
  },
  {
    train_id: "1161B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:19:00",
    color: "#E30A16",
    dest_time: "07:49:00",
  },
  {
    train_id: "1138B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "07:24:00",
    color: "#E30A16",
    dest_time: "08:22:00",
  },
  {
    train_id: "1011B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "07:25:00",
    color: "#E30A16",
    dest_time: "07:33:00",
  },
  {
    train_id: "1140C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "07:29:00",
    color: "#E30A16",
    dest_time: "08:00:00",
  },
  {
    train_id: "1163B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:29:00",
    color: "#E30A16",
    dest_time: "08:00:00",
  },
  {
    train_id: "1142B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "07:33:00",
    color: "#E30A16",
    dest_time: "08:33:00",
  },
  {
    train_id: "1165B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:34:00",
    color: "#E30A16",
    dest_time: "08:04:00",
  },
  {
    train_id: "1167B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:40:00",
    color: "#E30A16",
    dest_time: "08:11:00",
  },
  {
    train_id: "1146D",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "07:42:00",
    color: "#E30A16",
    dest_time: "08:12:00",
  },
  {
    train_id: "1169B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:43:00",
    color: "#E30A16",
    dest_time: "08:16:00",
  },
  {
    train_id: "1012B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "07:46:00",
    color: "#E30A16",
    dest_time: "08:44:00",
  },
  {
    train_id: "1013B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "07:50:00",
    color: "#E30A16",
    dest_time: "07:58:00",
  },
  {
    train_id: "1148B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "07:53:00",
    color: "#E30A16",
    dest_time: "08:54:00",
  },
  {
    train_id: "1171B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:54:00",
    color: "#E30A16",
    dest_time: "08:26:00",
  },
  {
    train_id: "1505C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "NAMBO-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:00:00",
    color: "#E30A16",
    dest_time: "08:30:00",
  },
  {
    train_id: "1150B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "08:01:00",
    color: "#E30A16",
    dest_time: "08:59:00",
  },
  {
    train_id: "1173B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:04:00",
    color: "#E30A16",
    dest_time: "08:38:00",
  },
  {
    train_id: "1152B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "08:06:00",
    color: "#E30A16",
    dest_time: "09:04:00",
  },
  {
    train_id: "1175B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:09:00",
    color: "#E30A16",
    dest_time: "08:42:00",
  },
  {
    train_id: "1154B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "08:10:00",
    color: "#E30A16",
    dest_time: "09:08:00",
  },
  {
    train_id: "1156B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "08:14:00",
    color: "#E30A16",
    dest_time: "09:13:00",
  },
  {
    train_id: "1177B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:14:00",
    color: "#E30A16",
    dest_time: "08:47:00",
  },
  {
    train_id: "1014B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "08:19:00",
    color: "#E30A16",
    dest_time: "09:18:00",
  },
  {
    train_id: "1015B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "08:20:00",
    color: "#E30A16",
    dest_time: "08:28:00",
  },
  {
    train_id: "1158B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "08:22:00",
    color: "#E30A16",
    dest_time: "08:56:00",
  },
  {
    train_id: "1179B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:24:00",
    color: "#E30A16",
    dest_time: "08:58:00",
  },
  {
    train_id: "1160B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "08:27:00",
    color: "#E30A16",
    dest_time: "09:28:00",
  },
  {
    train_id: "1181B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:31:00",
    color: "#E30A16",
    dest_time: "09:03:00",
  },
  {
    train_id: "1183B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:35:00",
    color: "#E30A16",
    dest_time: "09:07:00",
  },
  {
    train_id: "1162B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "08:36:00",
    color: "#E30A16",
    dest_time: "09:34:00",
  },
  {
    train_id: "1017B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "08:40:00",
    color: "#E30A16",
    dest_time: "08:51:00",
  },
  {
    train_id: "1016C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-DEPOK",
    dest: "DEPOK",
    time_est: "08:42:00",
    color: "#E30A16",
    dest_time: "09:12:00",
  },
  {
    train_id: "1164B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "08:45:00",
    color: "#E30A16",
    dest_time: "09:45:00",
  },
  {
    train_id: "1185B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:45:00",
    color: "#E30A16",
    dest_time: "09:16:00",
  },
  {
    train_id: "1166B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "08:49:00",
    color: "#E30A16",
    dest_time: "09:49:00",
  },
  {
    train_id: "1187B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:51:00",
    color: "#E30A16",
    dest_time: "09:21:00",
  },
  {
    train_id: "1189B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:54:00",
    color: "#E30A16",
    dest_time: "09:26:00",
  },
  {
    train_id: "1168B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "08:56:00",
    color: "#E30A16",
    dest_time: "09:54:00",
  },
  {
    train_id: "1191B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:59:00",
    color: "#E30A16",
    dest_time: "09:30:00",
  },
  {
    train_id: "1193B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:04:00",
    color: "#E30A16",
    dest_time: "09:35:00",
  },
  {
    train_id: "1018B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "09:07:00",
    color: "#E30A16",
    dest_time: "10:04:00",
  },
  {
    train_id: "1195B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:09:00",
    color: "#E30A16",
    dest_time: "09:40:00",
  },
  {
    train_id: "1508C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "09:11:00",
    color: "#E30A16",
    dest_time: "10:10:00",
  },
  {
    train_id: "1197B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:13:00",
    color: "#E30A16",
    dest_time: "09:44:00",
  },
  {
    train_id: "1172B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "09:14:00",
    color: "#E30A16",
    dest_time: "10:14:00",
  },
  {
    train_id: "1174C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "09:19:00",
    color: "#E30A16",
    dest_time: "09:52:00",
  },
  {
    train_id: "1019B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "09:21:00",
    color: "#E30A16",
    dest_time: "09:28:00",
  },
  {
    train_id: "1176B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "09:24:00",
    color: "#E30A16",
    dest_time: "10:24:00",
  },
  {
    train_id: "1199B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:25:00",
    color: "#E30A16",
    dest_time: "09:56:00",
  },
  {
    train_id: "1178B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "09:28:00",
    color: "#E30A16",
    dest_time: "10:29:00",
  },
  {
    train_id: "1507C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "NAMBO-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:30:00",
    color: "#E30A16",
    dest_time: "10:02:00",
  },
  {
    train_id: "1180B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "09:35:00",
    color: "#E30A16",
    dest_time: "10:33:00",
  },
  {
    train_id: "1201B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:39:00",
    color: "#E30A16",
    dest_time: "10:10:00",
  },
  {
    train_id: "1182C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "09:40:00",
    color: "#E30A16",
    dest_time: "10:11:00",
  },
  {
    train_id: "1020B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "09:44:00",
    color: "#E30A16",
    dest_time: "10:43:00",
  },
  {
    train_id: "1203B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:45:00",
    color: "#E30A16",
    dest_time: "10:15:00",
  },
  {
    train_id: "1023C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "09:51:00",
    color: "#E30A16",
    dest_time: "09:59:00",
  },
  {
    train_id: "1184B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "09:52:00",
    color: "#E30A16",
    dest_time: "10:49:00",
  },
  {
    train_id: "1186C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "09:57:00",
    color: "#E30A16",
    dest_time: "10:54:00",
  },
  {
    train_id: "1207B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:59:00",
    color: "#E30A16",
    dest_time: "10:29:00",
  },
  {
    train_id: "1188C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "10:06:00",
    color: "#E30A16",
    dest_time: "10:37:00",
  },
  {
    train_id: "1211B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:09:00",
    color: "#E30A16",
    dest_time: "10:39:00",
  },
  {
    train_id: "1190B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "10:10:00",
    color: "#E30A16",
    dest_time: "11:09:00",
  },
  {
    train_id: "1213B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:14:00",
    color: "#E30A16",
    dest_time: "10:44:00",
  },
  {
    train_id: "1192C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "10:15:00",
    color: "#E30A16",
    dest_time: "10:47:00",
  },
  {
    train_id: "1024B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "10:21:00",
    color: "#E30A16",
    dest_time: "11:19:00",
  },
  {
    train_id: "1215B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:21:00",
    color: "#E30A16",
    dest_time: "10:51:00",
  },
  {
    train_id: "1194B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "10:23:00",
    color: "#E30A16",
    dest_time: "11:24:00",
  },
  {
    train_id: "1196B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "10:27:00",
    color: "#E30A16",
    dest_time: "11:29:00",
  },
  {
    train_id: "1219B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:30:00",
    color: "#E30A16",
    dest_time: "11:00:00",
  },
  {
    train_id: "1198B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "10:35:00",
    color: "#E30A16",
    dest_time: "11:34:00",
  },
  {
    train_id: "1200B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "10:39:00",
    color: "#E30A16",
    dest_time: "11:39:00",
  },
  {
    train_id: "1223B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:40:00",
    color: "#E30A16",
    dest_time: "11:10:00",
  },
  {
    train_id: "1202B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "10:47:00",
    color: "#E30A16",
    dest_time: "11:17:00",
  },
  {
    train_id: "1025B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "10:50:00",
    color: "#E30A16",
    dest_time: "10:59:00",
  },
  {
    train_id: "1510C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "10:52:00",
    color: "#E30A16",
    dest_time: "11:50:00",
  },
  {
    train_id: "1227B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:54:00",
    color: "#E30A16",
    dest_time: "11:24:00",
  },
  {
    train_id: "1204B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "10:55:00",
    color: "#E30A16",
    dest_time: "11:54:00",
  },
  {
    train_id: "1229B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:59:00",
    color: "#E30A16",
    dest_time: "11:29:00",
  },
  {
    train_id: "1208B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "11:07:00",
    color: "#E30A16",
    dest_time: "12:04:00",
  },
  {
    train_id: "1233B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:09:00",
    color: "#E30A16",
    dest_time: "11:39:00",
  },
  {
    train_id: "1026B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "11:12:00",
    color: "#E30A16",
    dest_time: "12:09:00",
  },
  {
    train_id: "1509C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "NAMBO-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:14:00",
    color: "#E30A16",
    dest_time: "11:44:00",
  },
  {
    train_id: "1235B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:19:00",
    color: "#E30A16",
    dest_time: "11:48:00",
  },
  {
    train_id: "1212B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "11:22:00",
    color: "#E30A16",
    dest_time: "12:19:00",
  },
  {
    train_id: "1239B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:29:00",
    color: "#E30A16",
    dest_time: "12:04:00",
  },
  {
    train_id: "1216B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "11:32:00",
    color: "#E30A16",
    dest_time: "12:29:00",
  },
  {
    train_id: "1027B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "11:35:00",
    color: "#E30A16",
    dest_time: "11:43:00",
  },
  {
    train_id: "1241B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:39:00",
    color: "#E30A16",
    dest_time: "12:10:00",
  },
  {
    train_id: "1220B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "11:41:00",
    color: "#E30A16",
    dest_time: "12:13:00",
  },
  {
    train_id: "1029B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "11:50:00",
    color: "#E30A16",
    dest_time: "11:57:00",
  },
  {
    train_id: "1224B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "11:51:00",
    color: "#E30A16",
    dest_time: "12:48:00",
  },
  {
    train_id: "1245B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:54:00",
    color: "#E30A16",
    dest_time: "12:24:00",
  },
  {
    train_id: "1028B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "11:55:00",
    color: "#E30A16",
    dest_time: "12:53:00",
  },
  {
    train_id: "1249B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "12:05:00",
    color: "#E30A16",
    dest_time: "12:34:00",
  },
  {
    train_id: "1228B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "12:06:00",
    color: "#E30A16",
    dest_time: "13:03:00",
  },
  {
    train_id: "1230B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "12:12:00",
    color: "#E30A16",
    dest_time: "13:09:00",
  },
  {
    train_id: "1253B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "12:14:00",
    color: "#E30A16",
    dest_time: "12:45:00",
  },
  {
    train_id: "1030B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "12:21:00",
    color: "#E30A16",
    dest_time: "13:19:00",
  },
  {
    train_id: "1031B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "12:25:00",
    color: "#E30A16",
    dest_time: "12:33:00",
  },
  {
    train_id: "1512C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "12:25:00",
    color: "#E30A16",
    dest_time: "13:22:00",
  },
  {
    train_id: "1234B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "12:27:00",
    color: "#E30A16",
    dest_time: "13:28:00",
  },
  {
    train_id: "1257B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "12:29:00",
    color: "#E30A16",
    dest_time: "12:59:00",
  },
  {
    train_id: "1236B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "12:33:00",
    color: "#E30A16",
    dest_time: "13:33:00",
  },
  {
    train_id: "1261B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "12:39:00",
    color: "#E30A16",
    dest_time: "13:09:00",
  },
  {
    train_id: "1263B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "12:44:00",
    color: "#E30A16",
    dest_time: "13:14:00",
  },
  {
    train_id: "1240B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "12:46:00",
    color: "#E30A16",
    dest_time: "13:44:00",
  },
  {
    train_id: "1265B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "12:50:00",
    color: "#E30A16",
    dest_time: "13:19:00",
  },
  {
    train_id: "1032B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "12:51:00",
    color: "#E30A16",
    dest_time: "13:49:00",
  },
  {
    train_id: "1242B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "12:53:00",
    color: "#E30A16",
    dest_time: "13:53:00",
  },
  {
    train_id: "1511C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "NAMBO-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "12:54:00",
    color: "#E30A16",
    dest_time: "13:24:00",
  },
  {
    train_id: "1267B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "12:59:00",
    color: "#E30A16",
    dest_time: "13:28:00",
  },
  {
    train_id: "1246B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "13:06:00",
    color: "#E30A16",
    dest_time: "14:04:00",
  },
  {
    train_id: "1033B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "13:10:00",
    color: "#E30A16",
    dest_time: "13:18:00",
  },
  {
    train_id: "1271B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "13:14:00",
    color: "#E30A16",
    dest_time: "13:46:00",
  },
  {
    train_id: "1250B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "13:15:00",
    color: "#E30A16",
    dest_time: "14:14:00",
  },
  {
    train_id: "1275B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "13:24:00",
    color: "#E30A16",
    dest_time: "13:54:00",
  },
  {
    train_id: "1254B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "13:26:00",
    color: "#E30A16",
    dest_time: "14:24:00",
  },
  {
    train_id: "1034B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "13:33:00",
    color: "#E30A16",
    dest_time: "14:29:00",
  },
  {
    train_id: "1279B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "13:34:00",
    color: "#E30A16",
    dest_time: "14:05:00",
  },
  {
    train_id: "1258B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "13:42:00",
    color: "#E30A16",
    dest_time: "14:39:00",
  },
  {
    train_id: "1262B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "13:51:00",
    color: "#E30A16",
    dest_time: "14:49:00",
  },
  {
    train_id: "1035B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "13:55:00",
    color: "#E30A16",
    dest_time: "14:02:00",
  },
  {
    train_id: "1264B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "13:55:00",
    color: "#E30A16",
    dest_time: "14:54:00",
  },
  {
    train_id: "1266B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "13:59:00",
    color: "#E30A16",
    dest_time: "14:59:00",
  },
  {
    train_id: "1285B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "13:59:00",
    color: "#E30A16",
    dest_time: "14:30:00",
  },
  {
    train_id: "1514C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "14:06:00",
    color: "#E30A16",
    dest_time: "15:04:00",
  },
  {
    train_id: "1289B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:09:00",
    color: "#E30A16",
    dest_time: "14:39:00",
  },
  {
    train_id: "1268B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "14:11:00",
    color: "#E30A16",
    dest_time: "15:09:00",
  },
  {
    train_id: "1291B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:14:00",
    color: "#E30A16",
    dest_time: "14:44:00",
  },
  {
    train_id: "1036B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "14:17:00",
    color: "#E30A16",
    dest_time: "15:14:00",
  },
  {
    train_id: "1037B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "14:24:00",
    color: "#E30A16",
    dest_time: "14:31:00",
  },
  {
    train_id: "1272B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "14:25:00",
    color: "#E30A16",
    dest_time: "15:24:00",
  },
  {
    train_id: "1513C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "NAMBO-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:29:00",
    color: "#E30A16",
    dest_time: "14:59:00",
  },
  {
    train_id: "1295B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:34:00",
    color: "#E30A16",
    dest_time: "15:04:00",
  },
  {
    train_id: "1276B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "14:38:00",
    color: "#E30A16",
    dest_time: "15:35:00",
  },
  {
    train_id: "1297B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:39:00",
    color: "#E30A16",
    dest_time: "15:08:00",
  },
  {
    train_id: "1299C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:44:00",
    color: "#E30A16",
    dest_time: "15:13:00",
  },
  {
    train_id: "1280B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "14:47:00",
    color: "#E30A16",
    dest_time: "15:44:00",
  },
  {
    train_id: "1039B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "14:49:00",
    color: "#E30A16",
    dest_time: "14:56:00",
  },
  {
    train_id: "1038B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "14:52:00",
    color: "#E30A16",
    dest_time: "15:49:00",
  },
  {
    train_id: "1301B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:54:00",
    color: "#E30A16",
    dest_time: "15:25:00",
  },
  {
    train_id: "1303B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:59:00",
    color: "#E30A16",
    dest_time: "15:30:00",
  },
  {
    train_id: "1305C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:04:00",
    color: "#E30A16",
    dest_time: "15:37:00",
  },
  {
    train_id: "1040B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "15:08:00",
    color: "#E30A16",
    dest_time: "16:06:00",
  },
  {
    train_id: "1307B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:09:00",
    color: "#E30A16",
    dest_time: "15:41:00",
  },
  {
    train_id: "1286B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "15:11:00",
    color: "#E30A16",
    dest_time: "16:10:00",
  },
  {
    train_id: "1290B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "15:19:00",
    color: "#E30A16",
    dest_time: "16:19:00",
  },
  {
    train_id: "1041B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "15:20:00",
    color: "#E30A16",
    dest_time: "15:28:00",
  },
  {
    train_id: "1292B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "15:25:00",
    color: "#E30A16",
    dest_time: "16:24:00",
  },
  {
    train_id: "1313B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:29:00",
    color: "#E30A16",
    dest_time: "16:00:00",
  },
  {
    train_id: "1315B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:34:00",
    color: "#E30A16",
    dest_time: "16:04:00",
  },
  {
    train_id: "1296B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "15:39:00",
    color: "#E30A16",
    dest_time: "16:37:00",
  },
  {
    train_id: "1317C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:39:00",
    color: "#E30A16",
    dest_time: "16:10:00",
  },
  {
    train_id: "1298B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "15:43:00",
    color: "#E30A16",
    dest_time: "16:41:00",
  },
  {
    train_id: "1319B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:44:00",
    color: "#E30A16",
    dest_time: "16:18:00",
  },
  {
    train_id: "1042B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "15:48:00",
    color: "#E30A16",
    dest_time: "16:45:00",
  },
  {
    train_id: "1516C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "15:51:00",
    color: "#E30A16",
    dest_time: "16:50:00",
  },
  {
    train_id: "1321B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:54:00",
    color: "#E30A16",
    dest_time: "16:26:00",
  },
  {
    train_id: "1300B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "15:55:00",
    color: "#E30A16",
    dest_time: "16:53:00",
  },
  {
    train_id: "1302B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "15:59:00",
    color: "#E30A16",
    dest_time: "16:57:00",
  },
  {
    train_id: "1323B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:59:00",
    color: "#E30A16",
    dest_time: "16:30:00",
  },
  {
    train_id: "1325B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:04:00",
    color: "#E30A16",
    dest_time: "16:38:00",
  },
  {
    train_id: "1304B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:06:00",
    color: "#E30A16",
    dest_time: "17:04:00",
  },
  {
    train_id: "1515C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "NAMBO-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:10:00",
    color: "#E30A16",
    dest_time: "16:42:00",
  },
  {
    train_id: "1327B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:14:00",
    color: "#E30A16",
    dest_time: "16:46:00",
  },
  {
    train_id: "1306B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:16:00",
    color: "#E30A16",
    dest_time: "17:14:00",
  },
  {
    train_id: "1329B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:19:00",
    color: "#E30A16",
    dest_time: "16:51:00",
  },
  {
    train_id: "1308B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:20:00",
    color: "#E30A16",
    dest_time: "17:18:00",
  },
  {
    train_id: "1331C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:24:00",
    color: "#E30A16",
    dest_time: "17:00:00",
  },
  {
    train_id: "1045B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "16:30:00",
    color: "#E30A16",
    dest_time: "16:37:00",
  },
  {
    train_id: "1314B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:37:00",
    color: "#E30A16",
    dest_time: "17:34:00",
  },
  {
    train_id: "1335B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:39:00",
    color: "#E30A16",
    dest_time: "17:09:00",
  },
  {
    train_id: "1316B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:44:00",
    color: "#E30A16",
    dest_time: "17:42:00",
  },
  {
    train_id: "1318B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:48:00",
    color: "#E30A16",
    dest_time: "17:46:00",
  },
  {
    train_id: "1339B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:49:00",
    color: "#E30A16",
    dest_time: "17:18:00",
  },
  {
    train_id: "1046B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "16:53:00",
    color: "#E30A16",
    dest_time: "17:50:00",
  },
  {
    train_id: "1047B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "16:55:00",
    color: "#E30A16",
    dest_time: "17:02:00",
  },
  {
    train_id: "1320B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:55:00",
    color: "#E30A16",
    dest_time: "17:55:00",
  },
  {
    train_id: "1341B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:58:00",
    color: "#E30A16",
    dest_time: "17:30:00",
  },
  {
    train_id: "1322B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:59:00",
    color: "#E30A16",
    dest_time: "17:59:00",
  },
  {
    train_id: "1343B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:05:00",
    color: "#E30A16",
    dest_time: "17:38:00",
  },
  {
    train_id: "1324B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:06:00",
    color: "#E30A16",
    dest_time: "18:04:00",
  },
  {
    train_id: "1345B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:09:00",
    color: "#E30A16",
    dest_time: "17:42:00",
  },
  {
    train_id: "1048B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "17:14:00",
    color: "#E30A16",
    dest_time: "18:11:00",
  },
  {
    train_id: "1347B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:14:00",
    color: "#E30A16",
    dest_time: "17:46:00",
  },
  {
    train_id: "1326B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:17:00",
    color: "#E30A16",
    dest_time: "18:15:00",
  },
  {
    train_id: "1049C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "17:20:00",
    color: "#E30A16",
    dest_time: "17:28:00",
  },
  {
    train_id: "1328B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:21:00",
    color: "#E30A16",
    dest_time: "18:19:00",
  },
  {
    train_id: "1349C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:24:00",
    color: "#E30A16",
    dest_time: "17:55:00",
  },
  {
    train_id: "1330B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:25:00",
    color: "#E30A16",
    dest_time: "18:23:00",
  },
  {
    train_id: "1351B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:29:00",
    color: "#E30A16",
    dest_time: "18:02:00",
  },
  {
    train_id: "1518C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "17:32:00",
    color: "#E30A16",
    dest_time: "18:30:00",
  },
  {
    train_id: "1353C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "DEPOK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:35:00",
    color: "#E30A16",
    dest_time: "18:08:00",
  },
  {
    train_id: "1332B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:37:00",
    color: "#E30A16",
    dest_time: "18:34:00",
  },
  {
    train_id: "1355B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:40:00",
    color: "#E30A16",
    dest_time: "18:14:00",
  },
  {
    train_id: "1334B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:41:00",
    color: "#E30A16",
    dest_time: "18:38:00",
  },
  {
    train_id: "1050B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "17:46:00",
    color: "#E30A16",
    dest_time: "18:43:00",
  },
  {
    train_id: "1051B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "17:46:00",
    color: "#E30A16",
    dest_time: "17:56:00",
  },
  {
    train_id: "1336B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:49:00",
    color: "#E30A16",
    dest_time: "18:48:00",
  },
  {
    train_id: "1357B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:49:00",
    color: "#E30A16",
    dest_time: "18:20:00",
  },
  {
    train_id: "1338B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:53:00",
    color: "#E30A16",
    dest_time: "18:53:00",
  },
  {
    train_id: "1359B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:56:00",
    color: "#E30A16",
    dest_time: "18:28:00",
  },
  {
    train_id: "1340B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:00:00",
    color: "#E30A16",
    dest_time: "18:58:00",
  },
  {
    train_id: "1053B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "18:02:00",
    color: "#E30A16",
    dest_time: "18:10:00",
  },
  {
    train_id: "1342B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:04:00",
    color: "#E30A16",
    dest_time: "19:03:00",
  },
  {
    train_id: "1517C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "NAMBO-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:06:00",
    color: "#E30A16",
    dest_time: "18:35:00",
  },
  {
    train_id: "1052B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "18:09:00",
    color: "#E30A16",
    dest_time: "19:08:00",
  },
  {
    train_id: "1361B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:09:00",
    color: "#E30A16",
    dest_time: "18:39:00",
  },
  {
    train_id: "1344B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:14:00",
    color: "#E30A16",
    dest_time: "19:12:00",
  },
  {
    train_id: "1346B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:18:00",
    color: "#E30A16",
    dest_time: "19:16:00",
  },
  {
    train_id: "1365B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:19:00",
    color: "#E30A16",
    dest_time: "18:52:00",
  },
  {
    train_id: "1054B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "18:23:00",
    color: "#E30A16",
    dest_time: "19:20:00",
  },
  {
    train_id: "1367B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:24:00",
    color: "#E30A16",
    dest_time: "18:58:00",
  },
  {
    train_id: "1348B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:26:00",
    color: "#E30A16",
    dest_time: "19:24:00",
  },
  {
    train_id: "1350B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:31:00",
    color: "#E30A16",
    dest_time: "19:29:00",
  },
  {
    train_id: "1371B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:40:00",
    color: "#E30A16",
    dest_time: "19:12:00",
  },
  {
    train_id: "1352B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:41:00",
    color: "#E30A16",
    dest_time: "19:38:00",
  },
  {
    train_id: "1354B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:45:00",
    color: "#E30A16",
    dest_time: "19:43:00",
  },
  {
    train_id: "1373B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:46:00",
    color: "#E30A16",
    dest_time: "19:16:00",
  },
  {
    train_id: "1356B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:50:00",
    color: "#E30A16",
    dest_time: "19:48:00",
  },
  {
    train_id: "1375B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:51:00",
    color: "#E30A16",
    dest_time: "19:23:00",
  },
  {
    train_id: "1358B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:55:00",
    color: "#E30A16",
    dest_time: "19:53:00",
  },
  {
    train_id: "1377B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:55:00",
    color: "#E30A16",
    dest_time: "19:27:00",
  },
  {
    train_id: "1379B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:59:00",
    color: "#E30A16",
    dest_time: "19:31:00",
  },
  {
    train_id: "1057B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "19:05:00",
    color: "#E30A16",
    dest_time: "19:12:00",
  },
  {
    train_id: "1360B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "19:05:00",
    color: "#E30A16",
    dest_time: "20:03:00",
  },
  {
    train_id: "1520C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "19:09:00",
    color: "#E30A16",
    dest_time: "20:07:00",
  },
  {
    train_id: "1383B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:14:00",
    color: "#E30A16",
    dest_time: "19:45:00",
  },
  {
    train_id: "1362B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "19:16:00",
    color: "#E30A16",
    dest_time: "20:13:00",
  },
  {
    train_id: "1385B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:18:00",
    color: "#E30A16",
    dest_time: "19:49:00",
  },
  {
    train_id: "1387B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:24:00",
    color: "#E30A16",
    dest_time: "19:57:00",
  },
  {
    train_id: "1366B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "19:25:00",
    color: "#E30A16",
    dest_time: "20:25:00",
  },
  {
    train_id: "1058B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "19:30:00",
    color: "#E30A16",
    dest_time: "20:29:00",
  },
  {
    train_id: "1059B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "19:31:00",
    color: "#E30A16",
    dest_time: "19:39:00",
  },
  {
    train_id: "1368B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "19:34:00",
    color: "#E30A16",
    dest_time: "20:34:00",
  },
  {
    train_id: "1519C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "NAMBO-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:35:00",
    color: "#E30A16",
    dest_time: "20:05:00",
  },
  {
    train_id: "1389B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:39:00",
    color: "#E30A16",
    dest_time: "20:09:00",
  },
  {
    train_id: "1391B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:44:00",
    color: "#E30A16",
    dest_time: "20:15:00",
  },
  {
    train_id: "1372B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "19:46:00",
    color: "#E30A16",
    dest_time: "20:44:00",
  },
  {
    train_id: "1393B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:49:00",
    color: "#E30A16",
    dest_time: "20:23:00",
  },
  {
    train_id: "1374B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "19:52:00",
    color: "#E30A16",
    dest_time: "20:49:00",
  },
  {
    train_id: "1395B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:54:00",
    color: "#E30A16",
    dest_time: "20:27:00",
  },
  {
    train_id: "1060B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "19:57:00",
    color: "#E30A16",
    dest_time: "20:54:00",
  },
  {
    train_id: "1376B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "19:59:00",
    color: "#E30A16",
    dest_time: "20:59:00",
  },
  {
    train_id: "1397B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:59:00",
    color: "#E30A16",
    dest_time: "20:31:00",
  },
  {
    train_id: "1378B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "20:04:00",
    color: "#E30A16",
    dest_time: "21:04:00",
  },
  {
    train_id: "1061B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "20:10:00",
    color: "#E30A16",
    dest_time: "20:17:00",
  },
  {
    train_id: "1380B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "20:10:00",
    color: "#E30A16",
    dest_time: "21:09:00",
  },
  {
    train_id: "1401B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "20:15:00",
    color: "#E30A16",
    dest_time: "20:45:00",
  },
  {
    train_id: "1403B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "20:19:00",
    color: "#E30A16",
    dest_time: "20:49:00",
  },
  {
    train_id: "1384B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "20:24:00",
    color: "#E30A16",
    dest_time: "21:21:00",
  },
  {
    train_id: "1386B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "20:28:00",
    color: "#E30A16",
    dest_time: "21:25:00",
  },
  {
    train_id: "1388B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "20:32:00",
    color: "#E30A16",
    dest_time: "21:29:00",
  },
  {
    train_id: "1407B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "20:34:00",
    color: "#E30A16",
    dest_time: "21:04:00",
  },
  {
    train_id: "1062C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "MANGGARAI-BOGOR",
    dest: "BOGOR",
    time_est: "20:41:00",
    color: "#E30A16",
    dest_time: "21:39:00",
  },
  {
    train_id: "1390C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "20:42:00",
    color: "#E30A16",
    dest_time: "21:12:00",
  },
  {
    train_id: "1392B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "20:46:00",
    color: "#E30A16",
    dest_time: "21:43:00",
  },
  {
    train_id: "1522C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "20:51:00",
    color: "#E30A16",
    dest_time: "21:49:00",
  },
  {
    train_id: "1411B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "20:55:00",
    color: "#E30A16",
    dest_time: "21:25:00",
  },
  {
    train_id: "1394B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "21:00:00",
    color: "#E30A16",
    dest_time: "21:58:00",
  },
  {
    train_id: "1415B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "21:04:00",
    color: "#E30A16",
    dest_time: "21:34:00",
  },
  {
    train_id: "1396B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "21:07:00",
    color: "#E30A16",
    dest_time: "22:04:00",
  },
  {
    train_id: "1398B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "21:12:00",
    color: "#E30A16",
    dest_time: "22:09:00",
  },
  {
    train_id: "1419B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "21:20:00",
    color: "#E30A16",
    dest_time: "21:49:00",
  },
  {
    train_id: "1521C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "NAMBO-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "21:24:00",
    color: "#E30A16",
    dest_time: "21:54:00",
  },
  {
    train_id: "1402B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "21:28:00",
    color: "#E30A16",
    dest_time: "22:25:00",
  },
  {
    train_id: "1404B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "21:32:00",
    color: "#E30A16",
    dest_time: "22:29:00",
  },
  {
    train_id: "1423B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "21:34:00",
    color: "#E30A16",
    dest_time: "22:05:00",
  },
  {
    train_id: "1425B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "21:46:00",
    color: "#E30A16",
    dest_time: "22:16:00",
  },
  {
    train_id: "1408B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "21:47:00",
    color: "#E30A16",
    dest_time: "22:44:00",
  },
  {
    train_id: "1431B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "21:59:00",
    color: "#E30A16",
    dest_time: "22:30:00",
  },
  {
    train_id: "1412B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "22:02:00",
    color: "#E30A16",
    dest_time: "22:59:00",
  },
  {
    train_id: "1433B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "22:04:00",
    color: "#E30A16",
    dest_time: "22:34:00",
  },
  {
    train_id: "1414B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "22:11:00",
    color: "#E30A16",
    dest_time: "23:08:00",
  },
  {
    train_id: "1437B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "22:16:00",
    color: "#E30A16",
    dest_time: "22:46:00",
  },
  {
    train_id: "1418B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "22:24:00",
    color: "#E30A16",
    dest_time: "23:21:00",
  },
  {
    train_id: "1420B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "22:31:00",
    color: "#E30A16",
    dest_time: "23:28:00",
  },
  {
    train_id: "1443B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "22:34:00",
    color: "#E30A16",
    dest_time: "23:04:00",
  },
  {
    train_id: "1424B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "22:39:00",
    color: "#E30A16",
    dest_time: "23:36:00",
  },
  {
    train_id: "1426B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "22:50:00",
    color: "#E30A16",
    dest_time: "23:47:00",
  },
  {
    train_id: "1449B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "22:53:00",
    color: "#E30A16",
    dest_time: "23:23:00",
  },
  {
    train_id: "1523C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "NAMBO-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "22:59:00",
    color: "#E30A16",
    dest_time: "23:29:00",
  },
];

export async function GET() {
  const response = {
    status: 200,
    message: "Success",
    data: CW,
  };

  return NextResponse.json(response); // Mengembalikan respons JSON
}
