import { NextResponse } from "next/server";

const KPB = [
  {
    train_id: "4111",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "00:22:00",
    color: "#0084D8",
    dest_time: "00:27:00",
  },
  {
    train_id: "4000",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "JAKARTAKOTA-CIKARANG",
    dest: "CIKARANG",
    time_est: "04:27:00",
    color: "#0084D8",
    dest_time: "05:32:00",
  },
  {
    train_id: "5020",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "05:02:00",
    color: "#0084D8",
    dest_time: "06:04:00",
  },
  {
    train_id: "4002",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "JAKARTAKOTA-CIKARANG",
    dest: "CIKARANG",
    time_est: "05:10:00",
    color: "#0084D8",
    dest_time: "06:15:00",
  },
  {
    train_id: "5700",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "05:17:00",
    color: "#0084D8",
    dest_time: "05:49:00",
  },
  {
    train_id: "5024",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "05:26:00",
    color: "#0084D8",
    dest_time: "06:28:00",
  },
  {
    train_id: "4004",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "JAKARTAKOTA-BEKASI",
    dest: "BEKASI",
    time_est: "05:29:00",
    color: "#0084D8",
    dest_time: "06:13:00",
  },
  {
    train_id: "5502",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "05:45:00",
    color: "#0084D8",
    dest_time: "06:54:00",
  },
  {
    train_id: "4008",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-TAMBUN",
    dest: "TAMBUN",
    time_est: "05:46:00",
    color: "#0084D8",
    dest_time: "06:58:00",
  },
  {
    train_id: "5702",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "06:01:00",
    color: "#0084D8",
    dest_time: "06:33:00",
  },
  {
    train_id: "2400",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "06:07:00",
    color: "#DD0067",
    dest_time: "06:16:00",
  },
  {
    train_id: "5504",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "06:08:00",
    color: "#0084D8",
    dest_time: "06:55:00",
  },
  {
    train_id: "4010",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "06:16:00",
    color: "#0084D8",
    dest_time: "07:46:00",
  },
  {
    train_id: "5034A",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "06:24:00",
    color: "#0084D8",
    dest_time: "07:36:00",
  },
  {
    train_id: "2402A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "06:27:00",
    color: "#DD0067",
    dest_time: "06:36:00",
  },
  {
    train_id: "2401A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:36:00",
    color: "#DD0067",
    dest_time: "06:36:00",
  },
  {
    train_id: "5506",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "06:38:00",
    color: "#0084D8",
    dest_time: "07:24:00",
  },
  {
    train_id: "5038",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "06:41:00",
    color: "#0084D8",
    dest_time: "08:09:00",
  },
  {
    train_id: "4012A",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "06:45:00",
    color: "#0084D8",
    dest_time: "07:51:00",
  },
  {
    train_id: "2404A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "06:47:00",
    color: "#DD0067",
    dest_time: "06:56:00",
  },
  {
    train_id: "5508",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "06:55:00",
    color: "#0084D8",
    dest_time: "08:00:00",
  },
  {
    train_id: "2403A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:56:00",
    color: "#DD0067",
    dest_time: "06:56:00",
  },
  {
    train_id: "5040",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "07:01:00",
    color: "#0084D8",
    dest_time: "08:07:00",
  },
  {
    train_id: "2406A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "07:07:00",
    color: "#DD0067",
    dest_time: "07:16:00",
  },
  {
    train_id: "2405A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:16:00",
    color: "#DD0067",
    dest_time: "07:16:00",
  },
  {
    train_id: "4014",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "07:16:00",
    color: "#0084D8",
    dest_time: "08:46:00",
  },
  {
    train_id: "5510",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "07:18:00",
    color: "#0084D8",
    dest_time: "08:23:00",
  },
  {
    train_id: "5708",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "07:23:00",
    color: "#0084D8",
    dest_time: "07:54:00",
  },
  {
    train_id: "2408A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "07:27:00",
    color: "#DD0067",
    dest_time: "07:36:00",
  },
  {
    train_id: "4016",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "07:28:00",
    color: "#0084D8",
    dest_time: "08:50:00",
  },
  {
    train_id: "2407A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:36:00",
    color: "#DD0067",
    dest_time: "07:36:00",
  },
  {
    train_id: "5512",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "07:39:00",
    color: "#0084D8",
    dest_time: "08:26:00",
  },
  {
    train_id: "5046A",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "07:40:00",
    color: "#0084D8",
    dest_time: "09:14:00",
  },
  {
    train_id: "2410A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "07:47:00",
    color: "#DD0067",
    dest_time: "07:56:00",
  },
  {
    train_id: "5710",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "07:49:00",
    color: "#0084D8",
    dest_time: "08:21:00",
  },
  {
    train_id: "5514",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "07:51:00",
    color: "#0084D8",
    dest_time: "08:36:00",
  },
  {
    train_id: "2409A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:56:00",
    color: "#DD0067",
    dest_time: "07:56:00",
  },
  {
    train_id: "5516",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "08:00:00",
    color: "#0084D8",
    dest_time: "09:05:00",
  },
  {
    train_id: "5714A",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "08:01:00",
    color: "#0084D8",
    dest_time: "08:33:00",
  },
  {
    train_id: "2412A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "08:07:00",
    color: "#DD0067",
    dest_time: "08:16:00",
  },
  {
    train_id: "4020",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "08:12:00",
    color: "#0084D8",
    dest_time: "09:14:00",
  },
  {
    train_id: "2411A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:16:00",
    color: "#DD0067",
    dest_time: "08:16:00",
  },
  {
    train_id: "5520",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "08:23:00",
    color: "#0084D8",
    dest_time: "09:33:00",
  },
  {
    train_id: "4022",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "08:24:00",
    color: "#0084D8",
    dest_time: "10:00:00",
  },
  {
    train_id: "2414A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "08:27:00",
    color: "#DD0067",
    dest_time: "08:36:00",
  },
  {
    train_id: "5522",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "08:31:00",
    color: "#0084D8",
    dest_time: "09:38:00",
  },
  {
    train_id: "2413A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:36:00",
    color: "#DD0067",
    dest_time: "08:36:00",
  },
  {
    train_id: "5524",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "08:44:00",
    color: "#0084D8",
    dest_time: "09:49:00",
  },
  {
    train_id: "4024",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "08:45:00",
    color: "#0084D8",
    dest_time: "09:42:00",
  },
  {
    train_id: "2416A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "08:47:00",
    color: "#DD0067",
    dest_time: "08:56:00",
  },
  {
    train_id: "4026",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "08:54:00",
    color: "#0084D8",
    dest_time: "10:21:00",
  },
  {
    train_id: "2415A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:56:00",
    color: "#DD0067",
    dest_time: "08:56:00",
  },
  {
    train_id: "5526",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "09:01:00",
    color: "#0084D8",
    dest_time: "09:48:00",
  },
  {
    train_id: "2418A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "09:07:00",
    color: "#DD0067",
    dest_time: "09:16:00",
  },
  {
    train_id: "2417A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:16:00",
    color: "#DD0067",
    dest_time: "09:16:00",
  },
  {
    train_id: "5528",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "09:18:00",
    color: "#0084D8",
    dest_time: "10:08:00",
  },
  {
    train_id: "5720",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "09:18:00",
    color: "#0084D8",
    dest_time: "09:50:00",
  },
  {
    train_id: "4028",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "09:25:00",
    color: "#0084D8",
    dest_time: "10:48:00",
  },
  {
    train_id: "2420A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "09:27:00",
    color: "#DD0067",
    dest_time: "09:36:00",
  },
  {
    train_id: "2419A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:36:00",
    color: "#DD0067",
    dest_time: "09:36:00",
  },
  {
    train_id: "5530",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "09:38:00",
    color: "#0084D8",
    dest_time: "10:22:00",
  },
  {
    train_id: "5058",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "09:41:00",
    color: "#0084D8",
    dest_time: "10:44:00",
  },
  {
    train_id: "2422A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "09:47:00",
    color: "#DD0067",
    dest_time: "09:56:00",
  },
  {
    train_id: "4030A",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "09:49:00",
    color: "#0084D8",
    dest_time: "10:49:00",
  },
  {
    train_id: "5532",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "09:52:00",
    color: "#0084D8",
    dest_time: "11:04:00",
  },
  {
    train_id: "2421A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:56:00",
    color: "#DD0067",
    dest_time: "09:56:00",
  },
  {
    train_id: "2424A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "10:07:00",
    color: "#DD0067",
    dest_time: "10:16:00",
  },
  {
    train_id: "2423A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:16:00",
    color: "#DD0067",
    dest_time: "10:16:00",
  },
  {
    train_id: "4032A",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "10:18:00",
    color: "#0084D8",
    dest_time: "10:52:00",
  },
  {
    train_id: "5064",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "10:25:00",
    color: "#0084D8",
    dest_time: "11:28:00",
  },
  {
    train_id: "2426A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "10:27:00",
    color: "#DD0067",
    dest_time: "10:36:00",
  },
  {
    train_id: "5536",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "10:28:00",
    color: "#0084D8",
    dest_time: "11:12:00",
  },
  {
    train_id: "2425A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:36:00",
    color: "#DD0067",
    dest_time: "10:36:00",
  },
  {
    train_id: "4034",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "10:41:00",
    color: "#0084D8",
    dest_time: "11:44:00",
  },
  {
    train_id: "2428A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "10:47:00",
    color: "#DD0067",
    dest_time: "10:56:00",
  },
  {
    train_id: "4036A",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "10:52:00",
    color: "#0084D8",
    dest_time: "11:25:00",
  },
  {
    train_id: "5538",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "10:53:00",
    color: "#0084D8",
    dest_time: "12:00:00",
  },
  {
    train_id: "2427A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:56:00",
    color: "#DD0067",
    dest_time: "10:56:00",
  },
  {
    train_id: "5070",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "11:01:00",
    color: "#0084D8",
    dest_time: "12:03:00",
  },
  {
    train_id: "2430A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "11:07:00",
    color: "#DD0067",
    dest_time: "11:16:00",
  },
  {
    train_id: "4038B",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "11:13:00",
    color: "#0084D8",
    dest_time: "12:15:00",
  },
  {
    train_id: "2429A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:16:00",
    color: "#DD0067",
    dest_time: "11:16:00",
  },
  {
    train_id: "5540",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "11:25:00",
    color: "#0084D8",
    dest_time: "12:30:00",
  },
  {
    train_id: "2432A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "11:27:00",
    color: "#DD0067",
    dest_time: "11:36:00",
  },
  {
    train_id: "5074",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "11:31:00",
    color: "#0084D8",
    dest_time: "12:33:00",
  },
  {
    train_id: "2431A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:36:00",
    color: "#DD0067",
    dest_time: "11:36:00",
  },
  {
    train_id: "4040",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "11:42:00",
    color: "#0084D8",
    dest_time: "12:45:00",
  },
  {
    train_id: "2490B",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "11:43:00",
    color: "#DD0067",
    dest_time: "11:56:00",
  },
  {
    train_id: "5542",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "11:43:00",
    color: "#0084D8",
    dest_time: "12:48:00",
  },
  {
    train_id: "2433A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:56:00",
    color: "#DD0067",
    dest_time: "11:56:00",
  },
  {
    train_id: "5080",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "11:58:00",
    color: "#0084D8",
    dest_time: "13:22:00",
  },
  {
    train_id: "4042",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "12:10:00",
    color: "#0084D8",
    dest_time: "13:13:00",
  },
  {
    train_id: "2491B",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "12:12:00",
    color: "#DD0067",
    dest_time: "12:16:00",
  },
  {
    train_id: "5544",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "12:23:00",
    color: "#0084D8",
    dest_time: "13:29:00",
  },
  {
    train_id: "2438A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "12:27:00",
    color: "#DD0067",
    dest_time: "12:36:00",
  },
  {
    train_id: "4046",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "12:41:00",
    color: "#0084D8",
    dest_time: "14:02:00",
  },
  {
    train_id: "5546",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "12:47:00",
    color: "#0084D8",
    dest_time: "13:31:00",
  },
  {
    train_id: "5084A",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "12:52:00",
    color: "#0084D8",
    dest_time: "13:52:00",
  },
  {
    train_id: "2439A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "12:56:00",
    color: "#DD0067",
    dest_time: "12:56:00",
  },
  {
    train_id: "4048",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "12:56:00",
    color: "#0084D8",
    dest_time: "14:21:00",
  },
  {
    train_id: "2442A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "13:07:00",
    color: "#DD0067",
    dest_time: "13:16:00",
  },
  {
    train_id: "4050A",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "13:10:00",
    color: "#0084D8",
    dest_time: "14:13:00",
  },
  {
    train_id: "5090",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "13:17:00",
    color: "#0084D8",
    dest_time: "14:41:00",
  },
  {
    train_id: "5548",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "13:23:00",
    color: "#0084D8",
    dest_time: "14:08:00",
  },
  {
    train_id: "2444A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "13:27:00",
    color: "#DD0067",
    dest_time: "13:36:00",
  },
  {
    train_id: "4052",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "13:31:00",
    color: "#0084D8",
    dest_time: "14:58:00",
  },
  {
    train_id: "2443A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "13:36:00",
    color: "#DD0067",
    dest_time: "13:36:00",
  },
  {
    train_id: "2436B",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "13:43:00",
    color: "#DD0067",
    dest_time: "13:56:00",
  },
  {
    train_id: "5550A",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "13:45:00",
    color: "#0084D8",
    dest_time: "14:31:00",
  },
  {
    train_id: "5094B",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "13:47:00",
    color: "#0084D8",
    dest_time: "14:52:00",
  },
  {
    train_id: "2445A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "13:56:00",
    color: "#DD0067",
    dest_time: "13:56:00",
  },
  {
    train_id: "4056",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "14:01:00",
    color: "#0084D8",
    dest_time: "15:24:00",
  },
  {
    train_id: "5552",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "14:03:00",
    color: "#0084D8",
    dest_time: "14:47:00",
  },
  {
    train_id: "2448A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "14:07:00",
    color: "#DD0067",
    dest_time: "14:16:00",
  },
  {
    train_id: "2437B",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:12:00",
    color: "#DD0067",
    dest_time: "14:16:00",
  },
  {
    train_id: "4058",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "14:20:00",
    color: "#0084D8",
    dest_time: "15:50:00",
  },
  {
    train_id: "5736",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "14:26:00",
    color: "#0084D8",
    dest_time: "14:58:00",
  },
  {
    train_id: "2450A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "14:27:00",
    color: "#DD0067",
    dest_time: "14:36:00",
  },
  {
    train_id: "5102",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "14:31:00",
    color: "#0084D8",
    dest_time: "15:56:00",
  },
  {
    train_id: "5554",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "14:32:00",
    color: "#0084D8",
    dest_time: "15:18:00",
  },
  {
    train_id: "2449A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:36:00",
    color: "#DD0067",
    dest_time: "14:36:00",
  },
  {
    train_id: "2494B",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "14:43:00",
    color: "#DD0067",
    dest_time: "14:56:00",
  },
  {
    train_id: "5556",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "14:45:00",
    color: "#0084D8",
    dest_time: "15:29:00",
  },
  {
    train_id: "5104",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "14:46:00",
    color: "#0084D8",
    dest_time: "15:51:00",
  },
  {
    train_id: "2451A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:56:00",
    color: "#DD0067",
    dest_time: "14:56:00",
  },
  {
    train_id: "4060",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "14:56:00",
    color: "#0084D8",
    dest_time: "16:19:00",
  },
  {
    train_id: "2454A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "15:07:00",
    color: "#DD0067",
    dest_time: "15:16:00",
  },
  {
    train_id: "2495B",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:12:00",
    color: "#DD0067",
    dest_time: "15:16:00",
  },
  {
    train_id: "4062",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "15:20:00",
    color: "#0084D8",
    dest_time: "16:23:00",
  },
  {
    train_id: "2456A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "15:27:00",
    color: "#DD0067",
    dest_time: "15:36:00",
  },
  {
    train_id: "5560",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "15:31:00",
    color: "#0084D8",
    dest_time: "16:39:00",
  },
  {
    train_id: "2455A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:36:00",
    color: "#DD0067",
    dest_time: "15:36:00",
  },
  {
    train_id: "4064B",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "15:39:00",
    color: "#0084D8",
    dest_time: "16:43:00",
  },
  {
    train_id: "2496B",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "15:43:00",
    color: "#DD0067",
    dest_time: "15:56:00",
  },
  {
    train_id: "5562",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "15:49:00",
    color: "#0084D8",
    dest_time: "16:34:00",
  },
  {
    train_id: "2457A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:56:00",
    color: "#DD0067",
    dest_time: "15:56:00",
  },
  {
    train_id: "4066",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "16:01:00",
    color: "#0084D8",
    dest_time: "17:05:00",
  },
  {
    train_id: "5564",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "16:02:00",
    color: "#0084D8",
    dest_time: "17:11:00",
  },
  {
    train_id: "2460A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "16:07:00",
    color: "#DD0067",
    dest_time: "16:16:00",
  },
  {
    train_id: "2497B",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:12:00",
    color: "#DD0067",
    dest_time: "16:16:00",
  },
  {
    train_id: "4068",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "16:17:00",
    color: "#0084D8",
    dest_time: "17:22:00",
  },
  {
    train_id: "5120",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "16:23:00",
    color: "#0084D8",
    dest_time: "17:56:00",
  },
  {
    train_id: "2462A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "16:27:00",
    color: "#DD0067",
    dest_time: "16:36:00",
  },
  {
    train_id: "5566",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "16:28:00",
    color: "#0084D8",
    dest_time: "17:41:00",
  },
  {
    train_id: "2461A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:36:00",
    color: "#DD0067",
    dest_time: "16:36:00",
  },
  {
    train_id: "4070",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "16:40:00",
    color: "#0084D8",
    dest_time: "18:03:00",
  },
  {
    train_id: "2464A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "16:47:00",
    color: "#DD0067",
    dest_time: "16:56:00",
  },
  {
    train_id: "5568",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "16:47:00",
    color: "#0084D8",
    dest_time: "17:35:00",
  },
  {
    train_id: "4072",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "16:53:00",
    color: "#0084D8",
    dest_time: "18:16:00",
  },
  {
    train_id: "2463A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:56:00",
    color: "#DD0067",
    dest_time: "16:56:00",
  },
  {
    train_id: "4074",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "17:01:00",
    color: "#0084D8",
    dest_time: "18:06:00",
  },
  {
    train_id: "2466A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "17:07:00",
    color: "#DD0067",
    dest_time: "17:16:00",
  },
  {
    train_id: "5570",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "17:10:00",
    color: "#0084D8",
    dest_time: "18:21:00",
  },
  {
    train_id: "5126",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "17:11:00",
    color: "#0084D8",
    dest_time: "18:41:00",
  },
  {
    train_id: "2465A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:16:00",
    color: "#DD0067",
    dest_time: "17:16:00",
  },
  {
    train_id: "4076",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "17:19:00",
    color: "#0084D8",
    dest_time: "18:21:00",
  },
  {
    train_id: "5572",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "17:23:00",
    color: "#0084D8",
    dest_time: "18:32:00",
  },
  {
    train_id: "2468A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "17:27:00",
    color: "#DD0067",
    dest_time: "17:36:00",
  },
  {
    train_id: "5130",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "17:31:00",
    color: "#0084D8",
    dest_time: "18:33:00",
  },
  {
    train_id: "2467A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:36:00",
    color: "#DD0067",
    dest_time: "17:36:00",
  },
  {
    train_id: "2470A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "17:47:00",
    color: "#DD0067",
    dest_time: "17:56:00",
  },
  {
    train_id: "4078",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "17:48:00",
    color: "#0084D8",
    dest_time: "19:14:00",
  },
  {
    train_id: "5132",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "17:54:00",
    color: "#0084D8",
    dest_time: "18:58:00",
  },
  {
    train_id: "5574",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "17:54:00",
    color: "#0084D8",
    dest_time: "19:04:00",
  },
  {
    train_id: "2469A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:56:00",
    color: "#DD0067",
    dest_time: "17:56:00",
  },
  {
    train_id: "2472A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "18:07:00",
    color: "#DD0067",
    dest_time: "18:16:00",
  },
  {
    train_id: "2471A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:16:00",
    color: "#DD0067",
    dest_time: "18:16:00",
  },
  {
    train_id: "5576",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "18:18:00",
    color: "#0084D8",
    dest_time: "19:34:00",
  },
  {
    train_id: "4080",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "18:19:00",
    color: "#0084D8",
    dest_time: "19:41:00",
  },
  {
    train_id: "2474A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "18:27:00",
    color: "#DD0067",
    dest_time: "18:36:00",
  },
  {
    train_id: "4082",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "18:31:00",
    color: "#0084D8",
    dest_time: "19:55:00",
  },
  {
    train_id: "2473A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:36:00",
    color: "#DD0067",
    dest_time: "18:36:00",
  },
  {
    train_id: "4084",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "18:41:00",
    color: "#0084D8",
    dest_time: "19:45:00",
  },
  {
    train_id: "5578",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "18:45:00",
    color: "#0084D8",
    dest_time: "19:29:00",
  },
  {
    train_id: "2476A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "18:47:00",
    color: "#DD0067",
    dest_time: "18:56:00",
  },
  {
    train_id: "5140",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "18:51:00",
    color: "#0084D8",
    dest_time: "20:14:00",
  },
  {
    train_id: "4086",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "18:55:00",
    color: "#0084D8",
    dest_time: "20:19:00",
  },
  {
    train_id: "2475A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:56:00",
    color: "#DD0067",
    dest_time: "18:56:00",
  },
  {
    train_id: "2478A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "19:07:00",
    color: "#DD0067",
    dest_time: "19:16:00",
  },
  {
    train_id: "5142",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "19:11:00",
    color: "#0084D8",
    dest_time: "20:39:00",
  },
  {
    train_id: "2477A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:16:00",
    color: "#DD0067",
    dest_time: "19:16:00",
  },
  {
    train_id: "5582",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "19:17:00",
    color: "#0084D8",
    dest_time: "20:29:00",
  },
  {
    train_id: "5764",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "19:18:00",
    color: "#0084D8",
    dest_time: "19:50:00",
  },
  {
    train_id: "2480A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "19:27:00",
    color: "#DD0067",
    dest_time: "19:36:00",
  },
  {
    train_id: "2479A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:36:00",
    color: "#DD0067",
    dest_time: "19:36:00",
  },
  {
    train_id: "5584",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "19:40:00",
    color: "#0084D8",
    dest_time: "20:24:00",
  },
  {
    train_id: "4090",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "19:46:00",
    color: "#0084D8",
    dest_time: "20:52:00",
  },
  {
    train_id: "2482A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "19:47:00",
    color: "#DD0067",
    dest_time: "19:56:00",
  },
  {
    train_id: "4092",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "19:53:00",
    color: "#0084D8",
    dest_time: "21:02:00",
  },
  {
    train_id: "2481A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:56:00",
    color: "#DD0067",
    dest_time: "19:56:00",
  },
  {
    train_id: "5586",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "20:01:00",
    color: "#0084D8",
    dest_time: "21:10:00",
  },
  {
    train_id: "2484A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "20:07:00",
    color: "#DD0067",
    dest_time: "20:16:00",
  },
  {
    train_id: "4094",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "20:13:00",
    color: "#0084D8",
    dest_time: "21:44:00",
  },
  {
    train_id: "2483A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "20:16:00",
    color: "#DD0067",
    dest_time: "20:16:00",
  },
  {
    train_id: "5152",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "20:25:00",
    color: "#0084D8",
    dest_time: "21:54:00",
  },
  {
    train_id: "2486A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "20:27:00",
    color: "#DD0067",
    dest_time: "20:36:00",
  },
  {
    train_id: "2485A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "20:36:00",
    color: "#DD0067",
    dest_time: "20:36:00",
  },
  {
    train_id: "5776",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "20:41:00",
    color: "#0084D8",
    dest_time: "21:13:00",
  },
  {
    train_id: "2488A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "20:47:00",
    color: "#DD0067",
    dest_time: "20:56:00",
  },
  {
    train_id: "5156",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "20:47:00",
    color: "#0084D8",
    dest_time: "22:10:00",
  },
  {
    train_id: "5588",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "20:48:00",
    color: "#0084D8",
    dest_time: "21:33:00",
  },
  {
    train_id: "4098",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "20:55:00",
    color: "#0084D8",
    dest_time: "21:57:00",
  },
  {
    train_id: "2487A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "20:56:00",
    color: "#DD0067",
    dest_time: "20:56:00",
  },
  {
    train_id: "5590",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "21:00:00",
    color: "#0084D8",
    dest_time: "21:46:00",
  },
  {
    train_id: "4100",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "21:10:00",
    color: "#0084D8",
    dest_time: "22:34:00",
  },
  {
    train_id: "2489A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "TANJUNGPRIUK-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "21:16:00",
    color: "#DD0067",
    dest_time: "21:16:00",
  },
  {
    train_id: "5592",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "21:18:00",
    color: "#0084D8",
    dest_time: "22:07:00",
  },
  {
    train_id: "5160",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "21:24:00",
    color: "#0084D8",
    dest_time: "22:50:00",
  },
  {
    train_id: "4101",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "CIKARANG-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "21:33:00",
    color: "#0084D8",
    dest_time: "21:38:00",
  },
  {
    train_id: "5162",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "21:45:00",
    color: "#0084D8",
    dest_time: "23:05:00",
  },
  {
    train_id: "5594",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "21:46:00",
    color: "#0084D8",
    dest_time: "23:00:00",
  },
  {
    train_id: "5786",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "22:01:00",
    color: "#0084D8",
    dest_time: "22:33:00",
  },
  {
    train_id: "5596",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "22:08:00",
    color: "#0084D8",
    dest_time: "22:52:00",
  },
  {
    train_id: "5168",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-BEKASI",
    dest: "BEKASI",
    time_est: "22:15:00",
    color: "#0084D8",
    dest_time: "23:17:00",
  },
  {
    train_id: "5790",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "22:25:00",
    color: "#0084D8",
    dest_time: "22:58:00",
  },
  {
    train_id: "4106A",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "22:30:00",
    color: "#0084D8",
    dest_time: "23:02:00",
  },
  {
    train_id: "5598",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "22:38:00",
    color: "#0084D8",
    dest_time: "23:47:00",
  },
  {
    train_id: "4108",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "KAMPUNGBANDAN-CIKARANG",
    dest: "CIKARANG",
    time_est: "22:49:00",
    color: "#0084D8",
    dest_time: "00:18:00",
  },
];

export async function GET() {
  const response = {
    status: 200,
    message: "Success",
    data: KPB,
  };

  return NextResponse.json(response); // Mengembalikan respons JSON
}
