import { NextResponse } from "next/server";

const BOO = [
  {
    train_id: "1489B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-DEPOK",
    dest: "DEPOK",
    time_est: "00:19:00",
    color: "#E30A16",
    dest_time: "00:47:00",
  },
  {
    train_id: "1115B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "04:00:00",
    color: "#E30A16",
    dest_time: "05:25:00",
  },
  {
    train_id: "1119B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "04:10:00",
    color: "#E30A16",
    dest_time: "05:37:00",
  },
  {
    train_id: "1121B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "04:20:00",
    color: "#E30A16",
    dest_time: "05:45:00",
  },
  {
    train_id: "1123B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "04:25:00",
    color: "#E30A16",
    dest_time: "05:49:00",
  },
  {
    train_id: "1125B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "04:30:00",
    color: "#E30A16",
    dest_time: "05:53:00",
  },
  {
    train_id: "1127B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "04:35:00",
    color: "#E30A16",
    dest_time: "06:00:00",
  },
  {
    train_id: "1129B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "04:40:00",
    color: "#E30A16",
    dest_time: "06:05:00",
  },
  {
    train_id: "1333D",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "04:45:00",
    color: "#E30A16",
    dest_time: "05:47:00",
  },
  {
    train_id: "1131B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "04:50:00",
    color: "#E30A16",
    dest_time: "06:15:00",
  },
  {
    train_id: "1135B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "05:00:00",
    color: "#E30A16",
    dest_time: "06:28:00",
  },
  {
    train_id: "1137B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "05:05:00",
    color: "#E30A16",
    dest_time: "06:32:00",
  },
  {
    train_id: "1139B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "05:15:00",
    color: "#E30A16",
    dest_time: "06:41:00",
  },
  {
    train_id: "1143B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "05:25:00",
    color: "#E30A16",
    dest_time: "06:53:00",
  },
  {
    train_id: "1007B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "05:29:00",
    color: "#E30A16",
    dest_time: "06:31:00",
  },
  {
    train_id: "1147B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "05:41:00",
    color: "#E30A16",
    dest_time: "07:05:00",
  },
  {
    train_id: "1151B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "05:50:00",
    color: "#E30A16",
    dest_time: "07:17:00",
  },
  {
    train_id: "1009B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "05:55:00",
    color: "#E30A16",
    dest_time: "06:58:00",
  },
  {
    train_id: "1155B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:05:00",
    color: "#E30A16",
    dest_time: "07:32:00",
  },
  {
    train_id: "1157B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:15:00",
    color: "#E30A16",
    dest_time: "07:41:00",
  },
  {
    train_id: "1159B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:20:00",
    color: "#E30A16",
    dest_time: "07:45:00",
  },
  {
    train_id: "1161B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:25:00",
    color: "#E30A16",
    dest_time: "07:49:00",
  },
  {
    train_id: "1011B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "06:30:00",
    color: "#E30A16",
    dest_time: "07:33:00",
  },
  {
    train_id: "1163B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:35:00",
    color: "#E30A16",
    dest_time: "08:00:00",
  },
  {
    train_id: "1165B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:40:00",
    color: "#E30A16",
    dest_time: "08:04:00",
  },
  {
    train_id: "1169B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "06:49:00",
    color: "#E30A16",
    dest_time: "08:16:00",
  },
  {
    train_id: "1013B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "06:55:00",
    color: "#E30A16",
    dest_time: "07:58:00",
  },
  {
    train_id: "1171B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:00:00",
    color: "#E30A16",
    dest_time: "08:26:00",
  },
  {
    train_id: "1173B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:10:00",
    color: "#E30A16",
    dest_time: "08:38:00",
  },
  {
    train_id: "1175B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:15:00",
    color: "#E30A16",
    dest_time: "08:42:00",
  },
  {
    train_id: "1177B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:20:00",
    color: "#E30A16",
    dest_time: "08:47:00",
  },
  {
    train_id: "1015B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "07:25:00",
    color: "#E30A16",
    dest_time: "08:28:00",
  },
  {
    train_id: "1179B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:30:00",
    color: "#E30A16",
    dest_time: "08:58:00",
  },
  {
    train_id: "1181B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:37:00",
    color: "#E30A16",
    dest_time: "09:03:00",
  },
  {
    train_id: "1183B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:41:00",
    color: "#E30A16",
    dest_time: "09:07:00",
  },
  {
    train_id: "1017B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "07:46:00",
    color: "#E30A16",
    dest_time: "08:51:00",
  },
  {
    train_id: "1185B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "07:51:00",
    color: "#E30A16",
    dest_time: "09:16:00",
  },
  {
    train_id: "1189B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:00:00",
    color: "#E30A16",
    dest_time: "09:26:00",
  },
  {
    train_id: "1191B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:05:00",
    color: "#E30A16",
    dest_time: "09:30:00",
  },
  {
    train_id: "1193B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:10:00",
    color: "#E30A16",
    dest_time: "09:35:00",
  },
  {
    train_id: "1195B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:14:00",
    color: "#E30A16",
    dest_time: "09:40:00",
  },
  {
    train_id: "1197B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:19:00",
    color: "#E30A16",
    dest_time: "09:44:00",
  },
  {
    train_id: "1019B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "08:25:00",
    color: "#E30A16",
    dest_time: "09:28:00",
  },
  {
    train_id: "1199B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:31:00",
    color: "#E30A16",
    dest_time: "09:56:00",
  },
  {
    train_id: "1201B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "08:45:00",
    color: "#E30A16",
    dest_time: "10:10:00",
  },
  {
    train_id: "1023C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "08:55:00",
    color: "#E30A16",
    dest_time: "09:59:00",
  },
  {
    train_id: "1207B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:05:00",
    color: "#E30A16",
    dest_time: "10:29:00",
  },
  {
    train_id: "1211B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:15:00",
    color: "#E30A16",
    dest_time: "10:39:00",
  },
  {
    train_id: "1213B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:20:00",
    color: "#E30A16",
    dest_time: "10:44:00",
  },
  {
    train_id: "1215B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:27:00",
    color: "#E30A16",
    dest_time: "10:51:00",
  },
  {
    train_id: "1219B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:36:00",
    color: "#E30A16",
    dest_time: "11:00:00",
  },
  {
    train_id: "1223B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "09:46:00",
    color: "#E30A16",
    dest_time: "11:10:00",
  },
  {
    train_id: "1025B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "09:55:00",
    color: "#E30A16",
    dest_time: "10:59:00",
  },
  {
    train_id: "1227B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:00:00",
    color: "#E30A16",
    dest_time: "11:24:00",
  },
  {
    train_id: "1229B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:05:00",
    color: "#E30A16",
    dest_time: "11:29:00",
  },
  {
    train_id: "1233B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:15:00",
    color: "#E30A16",
    dest_time: "11:39:00",
  },
  {
    train_id: "1235B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:25:00",
    color: "#E30A16",
    dest_time: "11:48:00",
  },
  {
    train_id: "1239B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:35:00",
    color: "#E30A16",
    dest_time: "12:04:00",
  },
  {
    train_id: "1027B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "10:39:00",
    color: "#E30A16",
    dest_time: "11:43:00",
  },
  {
    train_id: "1241B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "10:45:00",
    color: "#E30A16",
    dest_time: "12:10:00",
  },
  {
    train_id: "1029B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "10:55:00",
    color: "#E30A16",
    dest_time: "11:57:00",
  },
  {
    train_id: "1245B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:00:00",
    color: "#E30A16",
    dest_time: "12:24:00",
  },
  {
    train_id: "1249B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:10:00",
    color: "#E30A16",
    dest_time: "12:34:00",
  },
  {
    train_id: "1253B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:20:00",
    color: "#E30A16",
    dest_time: "12:45:00",
  },
  {
    train_id: "1031B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "11:30:00",
    color: "#E30A16",
    dest_time: "12:33:00",
  },
  {
    train_id: "1257B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:35:00",
    color: "#E30A16",
    dest_time: "12:59:00",
  },
  {
    train_id: "1261B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:45:00",
    color: "#E30A16",
    dest_time: "13:09:00",
  },
  {
    train_id: "1263B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "11:50:00",
    color: "#E30A16",
    dest_time: "13:14:00",
  },
  {
    train_id: "1267B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "12:05:00",
    color: "#E30A16",
    dest_time: "13:28:00",
  },
  {
    train_id: "1033B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "12:15:00",
    color: "#E30A16",
    dest_time: "13:18:00",
  },
  {
    train_id: "1271B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "12:20:00",
    color: "#E30A16",
    dest_time: "13:46:00",
  },
  {
    train_id: "1275B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "12:30:00",
    color: "#E30A16",
    dest_time: "13:54:00",
  },
  {
    train_id: "1279B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "12:40:00",
    color: "#E30A16",
    dest_time: "14:05:00",
  },
  {
    train_id: "1035B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "13:00:00",
    color: "#E30A16",
    dest_time: "14:02:00",
  },
  {
    train_id: "1285B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "13:05:00",
    color: "#E30A16",
    dest_time: "14:30:00",
  },
  {
    train_id: "1289B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "13:15:00",
    color: "#E30A16",
    dest_time: "14:39:00",
  },
  {
    train_id: "1291B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "13:20:00",
    color: "#E30A16",
    dest_time: "14:44:00",
  },
  {
    train_id: "1037B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "13:29:00",
    color: "#E30A16",
    dest_time: "14:31:00",
  },
  {
    train_id: "1295B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "13:40:00",
    color: "#E30A16",
    dest_time: "15:04:00",
  },
  {
    train_id: "1297B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "13:45:00",
    color: "#E30A16",
    dest_time: "15:08:00",
  },
  {
    train_id: "1039B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "13:54:00",
    color: "#E30A16",
    dest_time: "14:56:00",
  },
  {
    train_id: "1301B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:00:00",
    color: "#E30A16",
    dest_time: "15:25:00",
  },
  {
    train_id: "1303B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:05:00",
    color: "#E30A16",
    dest_time: "15:30:00",
  },
  {
    train_id: "1307B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:15:00",
    color: "#E30A16",
    dest_time: "15:41:00",
  },
  {
    train_id: "1041B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "14:25:00",
    color: "#E30A16",
    dest_time: "15:28:00",
  },
  {
    train_id: "1313B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:35:00",
    color: "#E30A16",
    dest_time: "16:00:00",
  },
  {
    train_id: "1315B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:40:00",
    color: "#E30A16",
    dest_time: "16:04:00",
  },
  {
    train_id: "1319B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "14:50:00",
    color: "#E30A16",
    dest_time: "16:18:00",
  },
  {
    train_id: "1321B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:00:00",
    color: "#E30A16",
    dest_time: "16:26:00",
  },
  {
    train_id: "1323B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:05:00",
    color: "#E30A16",
    dest_time: "16:30:00",
  },
  {
    train_id: "1325B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:10:00",
    color: "#E30A16",
    dest_time: "16:38:00",
  },
  {
    train_id: "1327B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:20:00",
    color: "#E30A16",
    dest_time: "16:46:00",
  },
  {
    train_id: "1329B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:25:00",
    color: "#E30A16",
    dest_time: "16:51:00",
  },
  {
    train_id: "1045B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "15:35:00",
    color: "#E30A16",
    dest_time: "16:37:00",
  },
  {
    train_id: "1335B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:45:00",
    color: "#E30A16",
    dest_time: "17:09:00",
  },
  {
    train_id: "1339B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "15:55:00",
    color: "#E30A16",
    dest_time: "17:18:00",
  },
  {
    train_id: "1047B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "16:00:00",
    color: "#E30A16",
    dest_time: "17:02:00",
  },
  {
    train_id: "1341B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:04:00",
    color: "#E30A16",
    dest_time: "17:30:00",
  },
  {
    train_id: "1343B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:11:00",
    color: "#E30A16",
    dest_time: "17:38:00",
  },
  {
    train_id: "1345B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:15:00",
    color: "#E30A16",
    dest_time: "17:42:00",
  },
  {
    train_id: "1347B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:20:00",
    color: "#E30A16",
    dest_time: "17:46:00",
  },
  {
    train_id: "1349C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:29:00",
    color: "#E30A16",
    dest_time: "17:55:00",
  },
  {
    train_id: "1351B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:35:00",
    color: "#E30A16",
    dest_time: "18:02:00",
  },
  {
    train_id: "1355B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:46:00",
    color: "#E30A16",
    dest_time: "18:14:00",
  },
  {
    train_id: "1051B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "16:50:00",
    color: "#E30A16",
    dest_time: "17:56:00",
  },
  {
    train_id: "1357B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "16:55:00",
    color: "#E30A16",
    dest_time: "18:20:00",
  },
  {
    train_id: "1359B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:02:00",
    color: "#E30A16",
    dest_time: "18:28:00",
  },
  {
    train_id: "1053B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "17:06:00",
    color: "#E30A16",
    dest_time: "18:10:00",
  },
  {
    train_id: "1361B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:15:00",
    color: "#E30A16",
    dest_time: "18:39:00",
  },
  {
    train_id: "1365B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:25:00",
    color: "#E30A16",
    dest_time: "18:52:00",
  },
  {
    train_id: "1367B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:30:00",
    color: "#E30A16",
    dest_time: "18:58:00",
  },
  {
    train_id: "1371B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:45:00",
    color: "#E30A16",
    dest_time: "19:12:00",
  },
  {
    train_id: "1373B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:52:00",
    color: "#E30A16",
    dest_time: "19:16:00",
  },
  {
    train_id: "1375B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "17:57:00",
    color: "#E30A16",
    dest_time: "19:23:00",
  },
  {
    train_id: "1377B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:01:00",
    color: "#E30A16",
    dest_time: "19:27:00",
  },
  {
    train_id: "1379B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:05:00",
    color: "#E30A16",
    dest_time: "19:31:00",
  },
  {
    train_id: "1057B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "18:10:00",
    color: "#E30A16",
    dest_time: "19:12:00",
  },
  {
    train_id: "1381C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-DEPOK",
    dest: "DEPOK",
    time_est: "18:14:00",
    color: "#E30A16",
    dest_time: "18:42:00",
  },
  {
    train_id: "1383B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:20:00",
    color: "#E30A16",
    dest_time: "19:45:00",
  },
  {
    train_id: "1385B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:25:00",
    color: "#E30A16",
    dest_time: "19:49:00",
  },
  {
    train_id: "1387B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:30:00",
    color: "#E30A16",
    dest_time: "19:57:00",
  },
  {
    train_id: "1059B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "18:35:00",
    color: "#E30A16",
    dest_time: "19:39:00",
  },
  {
    train_id: "1389B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:45:00",
    color: "#E30A16",
    dest_time: "20:09:00",
  },
  {
    train_id: "1391B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:50:00",
    color: "#E30A16",
    dest_time: "20:15:00",
  },
  {
    train_id: "1393B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "18:55:00",
    color: "#E30A16",
    dest_time: "20:23:00",
  },
  {
    train_id: "1395B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:00:00",
    color: "#E30A16",
    dest_time: "20:27:00",
  },
  {
    train_id: "1397B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:05:00",
    color: "#E30A16",
    dest_time: "20:31:00",
  },
  {
    train_id: "1399C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-DEPOK",
    dest: "DEPOK",
    time_est: "19:09:00",
    color: "#E30A16",
    dest_time: "19:38:00",
  },
  {
    train_id: "1061B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "19:15:00",
    color: "#E30A16",
    dest_time: "20:17:00",
  },
  {
    train_id: "1401B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:21:00",
    color: "#E30A16",
    dest_time: "20:45:00",
  },
  {
    train_id: "1403B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:25:00",
    color: "#E30A16",
    dest_time: "20:49:00",
  },
  {
    train_id: "1405C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-DEPOK",
    dest: "DEPOK",
    time_est: "19:30:00",
    color: "#E30A16",
    dest_time: "19:58:00",
  },
  {
    train_id: "1063C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-DEPOK",
    dest: "DEPOK",
    time_est: "19:34:00",
    color: "#E30A16",
    dest_time: "20:02:00",
  },
  {
    train_id: "1407B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "19:39:00",
    color: "#E30A16",
    dest_time: "21:04:00",
  },
  {
    train_id: "1065C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-DEPOK",
    dest: "DEPOK",
    time_est: "19:55:00",
    color: "#E30A16",
    dest_time: "20:23:00",
  },
  {
    train_id: "1411B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "20:00:00",
    color: "#E30A16",
    dest_time: "21:25:00",
  },
  {
    train_id: "1413B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-DEPOK",
    dest: "DEPOK",
    time_est: "20:05:00",
    color: "#E30A16",
    dest_time: "20:33:00",
  },
  {
    train_id: "1415B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "20:10:00",
    color: "#E30A16",
    dest_time: "21:34:00",
  },
  {
    train_id: "1067C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-DEPOK",
    dest: "DEPOK",
    time_est: "20:22:00",
    color: "#E30A16",
    dest_time: "20:50:00",
  },
  {
    train_id: "1419B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "20:26:00",
    color: "#E30A16",
    dest_time: "21:49:00",
  },
  {
    train_id: "1423B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "20:40:00",
    color: "#E30A16",
    dest_time: "22:05:00",
  },
  {
    train_id: "1069C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-DEPOK",
    dest: "DEPOK",
    time_est: "20:46:00",
    color: "#E30A16",
    dest_time: "21:14:00",
  },
  {
    train_id: "1425B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "20:51:00",
    color: "#E30A16",
    dest_time: "22:16:00",
  },
  {
    train_id: "1427C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-DEPOK",
    dest: "DEPOK",
    time_est: "20:56:00",
    color: "#E30A16",
    dest_time: "21:23:00",
  },
  {
    train_id: "1429C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-DEPOK",
    dest: "DEPOK",
    time_est: "21:00:00",
    color: "#E30A16",
    dest_time: "21:28:00",
  },
  {
    train_id: "1431B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "21:05:00",
    color: "#E30A16",
    dest_time: "22:30:00",
  },
  {
    train_id: "1433B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "21:10:00",
    color: "#E30A16",
    dest_time: "22:34:00",
  },
  {
    train_id: "1435C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-DEPOK",
    dest: "DEPOK",
    time_est: "21:15:00",
    color: "#E30A16",
    dest_time: "21:43:00",
  },
  {
    train_id: "1437B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "21:22:00",
    color: "#E30A16",
    dest_time: "22:46:00",
  },
  {
    train_id: "1441B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-DEPOK",
    dest: "DEPOK",
    time_est: "21:31:00",
    color: "#E30A16",
    dest_time: "21:59:00",
  },
  {
    train_id: "1443B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "21:40:00",
    color: "#E30A16",
    dest_time: "23:04:00",
  },
  {
    train_id: "1445C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-DEPOK",
    dest: "DEPOK",
    time_est: "21:50:00",
    color: "#E30A16",
    dest_time: "22:18:00",
  },
  {
    train_id: "1449B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "21:59:00",
    color: "#E30A16",
    dest_time: "23:23:00",
  },
  {
    train_id: "1451C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-DEPOK",
    dest: "DEPOK",
    time_est: "22:12:00",
    color: "#E30A16",
    dest_time: "22:40:00",
  },
  {
    train_id: "1455B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "22:16:00",
    color: "#E30A16",
    dest_time: "23:40:00",
  },
  {
    train_id: "1457B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-DEPOK",
    dest: "DEPOK",
    time_est: "22:20:00",
    color: "#E30A16",
    dest_time: "22:48:00",
  },
  {
    train_id: "1463B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-DEPOK",
    dest: "DEPOK",
    time_est: "22:45:00",
    color: "#E30A16",
    dest_time: "23:13:00",
  },
  {
    train_id: "1465B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-DEPOK",
    dest: "DEPOK",
    time_est: "22:50:00",
    color: "#E30A16",
    dest_time: "23:18:00",
  },
  {
    train_id: "1467B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "BOGOR-JAKARTAKOTA",
    dest: "JAKARTAKOTA",
    time_est: "22:55:00",
    color: "#E30A16",
    dest_time: "00:20:00",
  },
];

export async function GET() {
  const response = {
    status: 200,
    message: "Success",
    data: BOO,
  };

  return NextResponse.json(response); // Mengembalikan respons JSON
}
