import { NextResponse } from "next/server";

const JAKK = [
  {
    train_id: "4000",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "JAKARTAKOTA-CIKARANG",
    dest: "CIKARANG",
    time_est: "04:20:00",
    color: "#0084D8",
    dest_time: "05:32:00",
  },
  {
    train_id: "D1/R5501-6",
    ka_name: "DINAS RANGKAIAN KRL (TIDAK ANGKUT PENUMPANG)",
    route_name: "JAKARTAKOTA-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "04:40:00",
    color: "#E30A16",
    dest_time: "04:58:00",
  },
  {
    train_id: "D1/R5016",
    ka_name: "DINAS RANGKAIAN KRL (TIDAK ANGKUT PENUMPANG)",
    route_name: "JAKARTAKOTA-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "04:52:00",
    color: "#E30A16",
    dest_time: "05:10:00",
  },
  {
    train_id: "4002",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "JAKARTAKOTA-CIKARANG",
    dest: "CIKARANG",
    time_est: "05:04:00",
    color: "#0084D8",
    dest_time: "06:15:00",
  },
  {
    train_id: "4004",
    ka_name: "COMMUTER LINE CIKARANG",
    route_name: "JAKARTAKOTA-BEKASI",
    dest: "BEKASI",
    time_est: "05:23:00",
    color: "#0084D8",
    dest_time: "06:13:00",
  },
  {
    train_id: "1504C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "05:26:00",
    color: "#E30A16",
    dest_time: "06:52:00",
  },
  {
    train_id: "1114B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "05:34:00",
    color: "#E30A16",
    dest_time: "06:58:00",
  },
  {
    train_id: "1118B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "05:46:00",
    color: "#E30A16",
    dest_time: "07:13:00",
  },
  {
    train_id: "1120B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "05:54:00",
    color: "#E30A16",
    dest_time: "07:18:00",
  },
  {
    train_id: "1122B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "05:58:00",
    color: "#E30A16",
    dest_time: "07:23:00",
  },
  {
    train_id: "2400",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "06:00:00",
    color: "#DD0067",
    dest_time: "06:16:00",
  },
  {
    train_id: "1124B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:02:00",
    color: "#E30A16",
    dest_time: "07:27:00",
  },
  {
    train_id: "1126B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:12:00",
    color: "#E30A16",
    dest_time: "07:35:00",
  },
  {
    train_id: "1128B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:20:00",
    color: "#E30A16",
    dest_time: "07:45:00",
  },
  {
    train_id: "2402A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "06:20:00",
    color: "#DD0067",
    dest_time: "06:36:00",
  },
  {
    train_id: "1130B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:25:00",
    color: "#E30A16",
    dest_time: "07:50:00",
  },
  {
    train_id: "1132B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:32:00",
    color: "#E30A16",
    dest_time: "07:57:00",
  },
  {
    train_id: "1134B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:38:00",
    color: "#E30A16",
    dest_time: "08:03:00",
  },
  {
    train_id: "2404A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "06:40:00",
    color: "#DD0067",
    dest_time: "06:56:00",
  },
  {
    train_id: "1136B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:44:00",
    color: "#E30A16",
    dest_time: "08:08:00",
  },
  {
    train_id: "1506C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "06:50:00",
    color: "#E30A16",
    dest_time: "08:16:00",
  },
  {
    train_id: "1138B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "06:58:00",
    color: "#E30A16",
    dest_time: "08:22:00",
  },
  {
    train_id: "2406A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "07:00:00",
    color: "#DD0067",
    dest_time: "07:16:00",
  },
  {
    train_id: "1140C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "07:02:00",
    color: "#E30A16",
    dest_time: "08:00:00",
  },
  {
    train_id: "1142B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "07:07:00",
    color: "#E30A16",
    dest_time: "08:33:00",
  },
  {
    train_id: "1146D",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "07:14:00",
    color: "#E30A16",
    dest_time: "08:12:00",
  },
  {
    train_id: "2408A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "07:20:00",
    color: "#DD0067",
    dest_time: "07:36:00",
  },
  {
    train_id: "1148B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "07:29:00",
    color: "#E30A16",
    dest_time: "08:54:00",
  },
  {
    train_id: "1150B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "07:33:00",
    color: "#E30A16",
    dest_time: "08:59:00",
  },
  {
    train_id: "1152B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "07:38:00",
    color: "#E30A16",
    dest_time: "09:04:00",
  },
  {
    train_id: "2410A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "07:40:00",
    color: "#DD0067",
    dest_time: "07:56:00",
  },
  {
    train_id: "1154B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "07:42:00",
    color: "#E30A16",
    dest_time: "09:08:00",
  },
  {
    train_id: "1156B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "07:46:00",
    color: "#E30A16",
    dest_time: "09:13:00",
  },
  {
    train_id: "1158B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "07:52:00",
    color: "#E30A16",
    dest_time: "08:56:00",
  },
  {
    train_id: "2412A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "08:00:00",
    color: "#DD0067",
    dest_time: "08:16:00",
  },
  {
    train_id: "1160B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "08:01:00",
    color: "#E30A16",
    dest_time: "09:28:00",
  },
  {
    train_id: "1162B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "08:08:00",
    color: "#E30A16",
    dest_time: "09:34:00",
  },
  {
    train_id: "1164B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "08:17:00",
    color: "#E30A16",
    dest_time: "09:45:00",
  },
  {
    train_id: "2414A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "08:20:00",
    color: "#DD0067",
    dest_time: "08:36:00",
  },
  {
    train_id: "1166B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "08:22:00",
    color: "#E30A16",
    dest_time: "09:49:00",
  },
  {
    train_id: "1168B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "08:31:00",
    color: "#E30A16",
    dest_time: "09:54:00",
  },
  {
    train_id: "D1/R1169B-2",
    ka_name: "DINAS RANGKAIAN KRL (TIDAK ANGKUT PENUMPANG)",
    route_name: "JAKARTAKOTA-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "08:35:00",
    color: "#E30A16",
    dest_time: "08:56:00",
  },
  {
    train_id: "1508C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "08:39:00",
    color: "#E30A16",
    dest_time: "10:10:00",
  },
  {
    train_id: "2416A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "08:40:00",
    color: "#DD0067",
    dest_time: "08:56:00",
  },
  {
    train_id: "1172B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "08:44:00",
    color: "#E30A16",
    dest_time: "10:14:00",
  },
  {
    train_id: "1174C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "08:51:00",
    color: "#E30A16",
    dest_time: "09:52:00",
  },
  {
    train_id: "1176B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "09:00:00",
    color: "#E30A16",
    dest_time: "10:24:00",
  },
  {
    train_id: "2418A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "09:00:00",
    color: "#DD0067",
    dest_time: "09:16:00",
  },
  {
    train_id: "1178B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "09:04:00",
    color: "#E30A16",
    dest_time: "10:29:00",
  },
  {
    train_id: "1180B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "09:09:00",
    color: "#E30A16",
    dest_time: "10:33:00",
  },
  {
    train_id: "1182C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "09:13:00",
    color: "#E30A16",
    dest_time: "10:11:00",
  },
  {
    train_id: "2420A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "09:20:00",
    color: "#DD0067",
    dest_time: "09:36:00",
  },
  {
    train_id: "1184B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "09:27:00",
    color: "#E30A16",
    dest_time: "10:49:00",
  },
  {
    train_id: "1186C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "09:31:00",
    color: "#E30A16",
    dest_time: "10:54:00",
  },
  {
    train_id: "1188C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "09:37:00",
    color: "#E30A16",
    dest_time: "10:37:00",
  },
  {
    train_id: "2422A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "09:40:00",
    color: "#DD0067",
    dest_time: "09:56:00",
  },
  {
    train_id: "1190B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "09:41:00",
    color: "#E30A16",
    dest_time: "11:09:00",
  },
  {
    train_id: "1192C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "09:48:00",
    color: "#E30A16",
    dest_time: "10:47:00",
  },
  {
    train_id: "1194B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "09:52:00",
    color: "#E30A16",
    dest_time: "11:24:00",
  },
  {
    train_id: "1196B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "09:59:00",
    color: "#E30A16",
    dest_time: "11:29:00",
  },
  {
    train_id: "2424A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "10:00:00",
    color: "#DD0067",
    dest_time: "10:16:00",
  },
  {
    train_id: "1198B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "10:11:00",
    color: "#E30A16",
    dest_time: "11:34:00",
  },
  {
    train_id: "1200B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "10:15:00",
    color: "#E30A16",
    dest_time: "11:39:00",
  },
  {
    train_id: "2426A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "10:20:00",
    color: "#DD0067",
    dest_time: "10:36:00",
  },
  {
    train_id: "1202B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "10:21:00",
    color: "#E30A16",
    dest_time: "11:17:00",
  },
  {
    train_id: "1510C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "10:26:00",
    color: "#E30A16",
    dest_time: "11:50:00",
  },
  {
    train_id: "1204B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "10:31:00",
    color: "#E30A16",
    dest_time: "11:54:00",
  },
  {
    train_id: "2428A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "10:40:00",
    color: "#DD0067",
    dest_time: "10:56:00",
  },
  {
    train_id: "1208B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "10:41:00",
    color: "#E30A16",
    dest_time: "12:04:00",
  },
  {
    train_id: "1212B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "10:56:00",
    color: "#E30A16",
    dest_time: "12:19:00",
  },
  {
    train_id: "2430A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "11:00:00",
    color: "#DD0067",
    dest_time: "11:16:00",
  },
  {
    train_id: "D1/R1213B-2",
    ka_name: "DINAS RANGKAIAN KRL (TIDAK ANGKUT PENUMPANG)",
    route_name: "JAKARTAKOTA-MANGGARAI",
    dest: "MANGGARAI",
    time_est: "11:01:00",
    color: "#E30A16",
    dest_time: "11:23:00",
  },
  {
    train_id: "1216B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "11:06:00",
    color: "#E30A16",
    dest_time: "12:29:00",
  },
  {
    train_id: "1220B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "11:15:00",
    color: "#E30A16",
    dest_time: "12:13:00",
  },
  {
    train_id: "2432A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "11:20:00",
    color: "#DD0067",
    dest_time: "11:36:00",
  },
  {
    train_id: "1224B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "11:25:00",
    color: "#E30A16",
    dest_time: "12:48:00",
  },
  {
    train_id: "1228B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "11:40:00",
    color: "#E30A16",
    dest_time: "13:03:00",
  },
  {
    train_id: "2490B",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "11:40:00",
    color: "#DD0067",
    dest_time: "11:56:00",
  },
  {
    train_id: "1230B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "11:45:00",
    color: "#E30A16",
    dest_time: "13:09:00",
  },
  {
    train_id: "1512C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "11:53:00",
    color: "#E30A16",
    dest_time: "13:22:00",
  },
  {
    train_id: "1234B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "12:01:00",
    color: "#E30A16",
    dest_time: "13:28:00",
  },
  {
    train_id: "1236B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "12:07:00",
    color: "#E30A16",
    dest_time: "13:33:00",
  },
  {
    train_id: "2438A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "12:20:00",
    color: "#DD0067",
    dest_time: "12:36:00",
  },
  {
    train_id: "1240B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "12:21:00",
    color: "#E30A16",
    dest_time: "13:44:00",
  },
  {
    train_id: "1242B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "12:25:00",
    color: "#E30A16",
    dest_time: "13:53:00",
  },
  {
    train_id: "1246B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "12:41:00",
    color: "#E30A16",
    dest_time: "14:04:00",
  },
  {
    train_id: "1250B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "12:51:00",
    color: "#E30A16",
    dest_time: "14:14:00",
  },
  {
    train_id: "1254B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "13:00:00",
    color: "#E30A16",
    dest_time: "14:24:00",
  },
  {
    train_id: "2442A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "13:00:00",
    color: "#DD0067",
    dest_time: "13:16:00",
  },
  {
    train_id: "1258B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "13:16:00",
    color: "#E30A16",
    dest_time: "14:39:00",
  },
  {
    train_id: "2444A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "13:20:00",
    color: "#DD0067",
    dest_time: "13:36:00",
  },
  {
    train_id: "1262B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "13:25:00",
    color: "#E30A16",
    dest_time: "14:49:00",
  },
  {
    train_id: "1264B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "13:30:00",
    color: "#E30A16",
    dest_time: "14:54:00",
  },
  {
    train_id: "1266B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "13:34:00",
    color: "#E30A16",
    dest_time: "14:59:00",
  },
  {
    train_id: "1514C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "13:38:00",
    color: "#E30A16",
    dest_time: "15:04:00",
  },
  {
    train_id: "2436B",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "13:40:00",
    color: "#DD0067",
    dest_time: "13:56:00",
  },
  {
    train_id: "1268B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "13:43:00",
    color: "#E30A16",
    dest_time: "15:09:00",
  },
  {
    train_id: "1272B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "14:00:00",
    color: "#E30A16",
    dest_time: "15:24:00",
  },
  {
    train_id: "2448A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "14:00:00",
    color: "#DD0067",
    dest_time: "14:16:00",
  },
  {
    train_id: "1276B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "14:10:00",
    color: "#E30A16",
    dest_time: "15:35:00",
  },
  {
    train_id: "2450A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "14:20:00",
    color: "#DD0067",
    dest_time: "14:36:00",
  },
  {
    train_id: "1280B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "14:21:00",
    color: "#E30A16",
    dest_time: "15:44:00",
  },
  {
    train_id: "2494B",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "14:40:00",
    color: "#DD0067",
    dest_time: "14:56:00",
  },
  {
    train_id: "1286B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "14:46:00",
    color: "#E30A16",
    dest_time: "16:10:00",
  },
  {
    train_id: "1290B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "14:55:00",
    color: "#E30A16",
    dest_time: "16:19:00",
  },
  {
    train_id: "1292B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "15:00:00",
    color: "#E30A16",
    dest_time: "16:24:00",
  },
  {
    train_id: "2454A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "15:00:00",
    color: "#DD0067",
    dest_time: "15:16:00",
  },
  {
    train_id: "1296B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "15:14:00",
    color: "#E30A16",
    dest_time: "16:37:00",
  },
  {
    train_id: "1298B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "15:18:00",
    color: "#E30A16",
    dest_time: "16:41:00",
  },
  {
    train_id: "2456A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "15:20:00",
    color: "#DD0067",
    dest_time: "15:36:00",
  },
  {
    train_id: "1516C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "15:22:00",
    color: "#E30A16",
    dest_time: "16:50:00",
  },
  {
    train_id: "1300B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "15:30:00",
    color: "#E30A16",
    dest_time: "16:53:00",
  },
  {
    train_id: "1302B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "15:34:00",
    color: "#E30A16",
    dest_time: "16:57:00",
  },
  {
    train_id: "1304B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "15:40:00",
    color: "#E30A16",
    dest_time: "17:04:00",
  },
  {
    train_id: "2496B",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "15:40:00",
    color: "#DD0067",
    dest_time: "15:56:00",
  },
  {
    train_id: "1306B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "15:47:00",
    color: "#E30A16",
    dest_time: "17:14:00",
  },
  {
    train_id: "1308B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "15:52:00",
    color: "#E30A16",
    dest_time: "17:18:00",
  },
  {
    train_id: "2460A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "16:00:00",
    color: "#DD0067",
    dest_time: "16:16:00",
  },
  {
    train_id: "1314B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:11:00",
    color: "#E30A16",
    dest_time: "17:34:00",
  },
  {
    train_id: "1316B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:19:00",
    color: "#E30A16",
    dest_time: "17:42:00",
  },
  {
    train_id: "2462A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "16:20:00",
    color: "#DD0067",
    dest_time: "16:36:00",
  },
  {
    train_id: "1318B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:23:00",
    color: "#E30A16",
    dest_time: "17:46:00",
  },
  {
    train_id: "1320B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:31:00",
    color: "#E30A16",
    dest_time: "17:55:00",
  },
  {
    train_id: "1322B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:35:00",
    color: "#E30A16",
    dest_time: "17:59:00",
  },
  {
    train_id: "1324B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:39:00",
    color: "#E30A16",
    dest_time: "18:04:00",
  },
  {
    train_id: "2464A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "16:40:00",
    color: "#DD0067",
    dest_time: "16:56:00",
  },
  {
    train_id: "1326B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:49:00",
    color: "#E30A16",
    dest_time: "18:15:00",
  },
  {
    train_id: "1328B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:53:00",
    color: "#E30A16",
    dest_time: "18:19:00",
  },
  {
    train_id: "1330B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "16:57:00",
    color: "#E30A16",
    dest_time: "18:23:00",
  },
  {
    train_id: "2466A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "17:00:00",
    color: "#DD0067",
    dest_time: "17:16:00",
  },
  {
    train_id: "1518C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "17:02:00",
    color: "#E30A16",
    dest_time: "18:30:00",
  },
  {
    train_id: "1332B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:11:00",
    color: "#E30A16",
    dest_time: "18:34:00",
  },
  {
    train_id: "1334B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:15:00",
    color: "#E30A16",
    dest_time: "18:38:00",
  },
  {
    train_id: "2468A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "17:20:00",
    color: "#DD0067",
    dest_time: "17:36:00",
  },
  {
    train_id: "1336B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:23:00",
    color: "#E30A16",
    dest_time: "18:48:00",
  },
  {
    train_id: "1338B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:27:00",
    color: "#E30A16",
    dest_time: "18:53:00",
  },
  {
    train_id: "1340B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:31:00",
    color: "#E30A16",
    dest_time: "18:58:00",
  },
  {
    train_id: "1342B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:38:00",
    color: "#E30A16",
    dest_time: "19:03:00",
  },
  {
    train_id: "2470A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "17:40:00",
    color: "#DD0067",
    dest_time: "17:56:00",
  },
  {
    train_id: "1344B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:47:00",
    color: "#E30A16",
    dest_time: "19:12:00",
  },
  {
    train_id: "1346B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:52:00",
    color: "#E30A16",
    dest_time: "19:16:00",
  },
  {
    train_id: "1348B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "17:59:00",
    color: "#E30A16",
    dest_time: "19:24:00",
  },
  {
    train_id: "2472A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "18:00:00",
    color: "#DD0067",
    dest_time: "18:16:00",
  },
  {
    train_id: "1350B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:05:00",
    color: "#E30A16",
    dest_time: "19:29:00",
  },
  {
    train_id: "1352B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:11:00",
    color: "#E30A16",
    dest_time: "19:38:00",
  },
  {
    train_id: "2474A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "18:20:00",
    color: "#DD0067",
    dest_time: "18:36:00",
  },
  {
    train_id: "1354B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:21:00",
    color: "#E30A16",
    dest_time: "19:43:00",
  },
  {
    train_id: "1356B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:25:00",
    color: "#E30A16",
    dest_time: "19:48:00",
  },
  {
    train_id: "1358B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:30:00",
    color: "#E30A16",
    dest_time: "19:53:00",
  },
  {
    train_id: "1360B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:40:00",
    color: "#E30A16",
    dest_time: "20:03:00",
  },
  {
    train_id: "2476A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "18:40:00",
    color: "#DD0067",
    dest_time: "18:56:00",
  },
  {
    train_id: "1520C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "18:44:00",
    color: "#E30A16",
    dest_time: "20:07:00",
  },
  {
    train_id: "1362B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "18:48:00",
    color: "#E30A16",
    dest_time: "20:13:00",
  },
  {
    train_id: "1366B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "19:00:00",
    color: "#E30A16",
    dest_time: "20:25:00",
  },
  {
    train_id: "2478A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "19:00:00",
    color: "#DD0067",
    dest_time: "19:16:00",
  },
  {
    train_id: "1368B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "19:09:00",
    color: "#E30A16",
    dest_time: "20:34:00",
  },
  {
    train_id: "1372B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "19:20:00",
    color: "#E30A16",
    dest_time: "20:44:00",
  },
  {
    train_id: "2480A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "19:20:00",
    color: "#DD0067",
    dest_time: "19:36:00",
  },
  {
    train_id: "1374B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "19:27:00",
    color: "#E30A16",
    dest_time: "20:49:00",
  },
  {
    train_id: "1376B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "19:34:00",
    color: "#E30A16",
    dest_time: "20:59:00",
  },
  {
    train_id: "1378B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "19:38:00",
    color: "#E30A16",
    dest_time: "21:04:00",
  },
  {
    train_id: "2482A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "19:40:00",
    color: "#DD0067",
    dest_time: "19:56:00",
  },
  {
    train_id: "1380B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "19:46:00",
    color: "#E30A16",
    dest_time: "21:09:00",
  },
  {
    train_id: "1384B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "19:58:00",
    color: "#E30A16",
    dest_time: "21:21:00",
  },
  {
    train_id: "2484A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "20:00:00",
    color: "#DD0067",
    dest_time: "20:16:00",
  },
  {
    train_id: "1386B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "20:02:00",
    color: "#E30A16",
    dest_time: "21:25:00",
  },
  {
    train_id: "1388B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "20:06:00",
    color: "#E30A16",
    dest_time: "21:29:00",
  },
  {
    train_id: "1390C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-DEPOK",
    dest: "DEPOK",
    time_est: "20:14:00",
    color: "#E30A16",
    dest_time: "21:12:00",
  },
  {
    train_id: "1392B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "20:20:00",
    color: "#E30A16",
    dest_time: "21:43:00",
  },
  {
    train_id: "2486A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "20:20:00",
    color: "#DD0067",
    dest_time: "20:36:00",
  },
  {
    train_id: "1522C",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-NAMBO",
    dest: "NAMBO",
    time_est: "20:24:00",
    color: "#E30A16",
    dest_time: "21:49:00",
  },
  {
    train_id: "1394B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "20:35:00",
    color: "#E30A16",
    dest_time: "21:58:00",
  },
  {
    train_id: "2488A",
    ka_name: "COMMUTER LINE TANJUNGPRIUK",
    route_name: "JAKARTAKOTA-TANJUNGPRIUK",
    dest: "TANJUNGPRIUK",
    time_est: "20:40:00",
    color: "#DD0067",
    dest_time: "20:56:00",
  },
  {
    train_id: "1396B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "20:41:00",
    color: "#E30A16",
    dest_time: "22:04:00",
  },
  {
    train_id: "1398B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "20:46:00",
    color: "#E30A16",
    dest_time: "22:09:00",
  },
  {
    train_id: "1402B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "21:00:00",
    color: "#E30A16",
    dest_time: "22:25:00",
  },
  {
    train_id: "1404B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "21:06:00",
    color: "#E30A16",
    dest_time: "22:29:00",
  },
  {
    train_id: "1408B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "21:21:00",
    color: "#E30A16",
    dest_time: "22:44:00",
  },
  {
    train_id: "1412B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "21:36:00",
    color: "#E30A16",
    dest_time: "22:59:00",
  },
  {
    train_id: "1414B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "21:45:00",
    color: "#E30A16",
    dest_time: "23:08:00",
  },
  {
    train_id: "1418B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "21:58:00",
    color: "#E30A16",
    dest_time: "23:21:00",
  },
  {
    train_id: "1420B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "22:05:00",
    color: "#E30A16",
    dest_time: "23:28:00",
  },
  {
    train_id: "1424B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "22:13:00",
    color: "#E30A16",
    dest_time: "23:36:00",
  },
  {
    train_id: "1426B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "22:24:00",
    color: "#E30A16",
    dest_time: "23:47:00",
  },
  {
    train_id: "1432B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "22:40:00",
    color: "#E30A16",
    dest_time: "00:03:00",
  },
  {
    train_id: "1434B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "22:50:00",
    color: "#E30A16",
    dest_time: "00:12:00",
  },
  {
    train_id: "1438B",
    ka_name: "COMMUTER LINE BOGOR",
    route_name: "JAKARTAKOTA-BOGOR",
    dest: "BOGOR",
    time_est: "23:00:00",
    color: "#E30A16",
    dest_time: "00:23:00",
  },
];

export async function GET() {
  const response = {
    status: 200,
    message: "Success",
    data: JAKK,
  };

  return NextResponse.json(response); // Mengembalikan respons JSON
}
